### PR TITLE
[weather.multi] 0.0.27

### PR DESCRIPTION
**Pull request by ronie**
### Description
the addon no longer works on new installs due to changes at Yahoo.
while it continues to work on existing installs (for now...), 
mark it as broken to prevent users from installing this addon.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Review by romanvm — APPROVED** [review]

**Review by romanvm — APPROVED** [review]

**Comment by Martii** [comment]
@ronie,

Would you please explain the "new user" bit here? 

I've already had this addon installed for a long time and got the notice that it was being disabled even though I'm an anonymous user i.e. I don't have an API key... I  usually get the temperature in my US region. After it was abruptly "recalled" by disabling I reenable it and it works just fine, anonymously. Even in the Weather "tab" it is still showing my extended forecast.

Thank you for taking some time to clarify why it was necessary to disable anonymous users of Multi Weather from being able to see their forecasts.

**Comment by ronie** [comment]
the addon will continue to work on existing installs,
but it will fail if you install it now.

**Comment by Martii** [comment]
@ronie 

> but it will fail if you install it now.

Are you claiming I can add it into an existing Kodi (fresh or otherwise) then it will fail?

**Comment by Martii** [comment]
@ronie

Confirmed that the question *(Kodi is unable to add it in)* is self-answered **because this commit removed it**.

Again I reask "Thank you for taking some time to clarify why it was necessary to disable anonymous users of Multi Weather from being able to see their forecasts.". 

This is not applicable as an anonymous user without an API key. i.e. the Weather App has been disabled by Kodi itself even though the usual primary usage of it still works.

Ref(s) found:
* https://github.com/xbmc/repo-scripts/issues/2225
* https://forum.kodi.tv/showthread.php?tid=352028&pid=3086785#pid3086785

**Comment by ronie** [comment]
@Martii please use the forum for discussions, github isn't the place for it.
(it sends out notifications to too many kodi devs with every message posted here).

**Comment by Martii** [comment]
n/m

> ronie correctly marked the add-on as broken with useful information that states that only users with old+valid cookie data will still be able to fetch weather data.
Not doing this would not be a better solution because other users might ask why the add-on is not marked as broken when it clearly is in some way.

Ca. https://forum.kodi.tv/showthread.php?tid=352028&pid=3203275#pid3203275 

i.e. cookie based requests are broken so the whole thing is marked as broken. Kodi add-on structure should really refine this down for those who use a portion of this who only utilize anonymous.


Too bad you couldn't have put this in here in the PR. Reputation withstanding affected.

**Comment by Martii** [comment]
@ronie 

> (it sends out notifications to too many kodi devs with every message posted here).

I'm aware of that. As I've already had a bad experience on the forum I choose here instead where the problem lies. GH is my preferred way of communicating with the devs as there is less b.s.

Thank you for the suggestion though.

**Pull request merged**
