### PR TITLE
[script.module.srgssr] v1.5.0

### PR DESCRIPTION
**Pull request by goggle**
### Description
Library that provides all the functions independent from the business unit of my SRG SSR related Kodi plugins. Will be used in `plugin.video.srfplaytv`, `plugin.video.rtsplaytv`, etc.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] v1.0.0

Additional information :
- Must be merged before `plugin.video.srfplaytv` v1.5.0.

### CODE REVIEW

**Comment by goggle** [comment]
@TravisBuddy Previous PR #1021 solves that issue.

**Comment by Rechi** [comment]
@goggle this add-on isn't Python 3 compatible. New add-ons have to be Python 3 compatible.
Have a look at https://kodi.tv/article/attention-addon-developers-migration-python-3 for more information.

**Comment by goggle** [comment]
@Rechi Could you tell me what the problems are? I have successfully tested `plugin.video.srfplaytv` (which uses `script.module.srgssr` and `script.module.youtube_channels`) on a Python 3 build, but with a modified version of the dependency `script.module.simplecache`, which does not seem to be Python 3 compatible yet.

Since `script.module.simplecache` is not a addon of my own, there is not much that I can do in this regard. I have already filed in a pull request for this matter (see here: https://github.com/kodi-community-addons/script.module.simplecache/pull/7), but did not get any response yet.

So is it necessary that also all the dependencies must be Python 3 compatible before new things can be merged into this repository? What would you suggest?

**Comment by Rechi** [comment]
It's great that you have already Python 3 compatibility checks.
\
During a quick test I've got an exception in `script.module.simplecache`, because it's not Python 3 compatible. I'm aware that it isn't your add-on, but you are using it and so your add-on also isn't Python 3 compatible. So you have to wait till it is updated or stop using it in this add-on.

**Comment by goggle** [comment]
Ok good, I didn't know that also the dependencies must be Python 3 ready at this stage.
So I think I will include a dummy representation of `script.module.simplecache` until this module is Python 3 ready.

What is the best way to check if the plugin runs in a Python 3 environment? I'd like to do something like this:
```
if PLUGIN_RUNS_IN_PYTHON_3_ENVIRONMENT:
    import DummyCache as SimpleCache
else:
    import SimpleCache
```

**Comment by goggle** [comment]
I just found that `platform.python_version_tuple()` should be able to do this. I will implement my suggested changes and push it on this branch soon.

**Comment by Rechi** [comment]
`if sys.version_info[0] >= 3`

**Comment by goggle** [comment]
Ok thanks, I'll use this one.

**Comment by goggle** [comment]
I have made the modifications to make the code fully work in Python 3 as well. Let me know if I should squash the commits.

**Comment by Rechi** [comment]
@goggle I assume you are running a modified version of script.module.inputstreamhelper too, with something like https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/38?

**Comment by goggle** [comment]
@Rechi I don't know. To test the Python 3 stuff I'm using my own build from the `feature_python3` branch here: https://github.com/xbmc/xbmc/tree/feature_python3

The only thing about `script.module.inputstreamhelper` that I've found in the logs is this:
```
2019-03-13 13:50:38.086 T:140225668784512  NOTICE: ADDON: kodi.binary.instance.inputstream v2.0.8 installed
```

Do you still encounter any problems?

**Comment by Rechi** [comment]
After reinstalling YouTube / removing YouTube settings it worked. But you should keep that in mind and convince the script.module.inputstreamhelper maintainer to push and update.


> Each add-on submission should be a single commit with using the following style: [script.foo.bar] v1.0.0

Please squash your commits.

**Comment by goggle** [comment]
Thanks, I hope now everything is ok.

**Pull request merged**
