### PR TITLE
[script.module.streamlink] 0.2.0

### PR DESCRIPTION
**Pull request by sophof**
### Description
Intended to replace the livestreamer module, since livestreamer was discontinued. [Streamlink](https://github.com/streamlink/streamlink) is a fork that is now actively developed. Will also upload a simple example plugin to the main repo called 'streamlink-player'.
### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [sciprt.foo.bar] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by sophof** [comment]
I just realised that streamlink has an extra dependency, namely pyCryptodome. There is no Kodi module for that, what would be the best way to add it? Just add it to the lib folder of this module, or make a separate module and include it in the addon.xml?

**Comment by phil65** [comment]
you have to wait how this here plays out: https://github.com/xbmc/xbmc/pull/11477

**Comment by sophof** [comment]
Ah, that's even better, since I just realised it wasn't trivial (requires C compiling for each target apparently). Still very much a beginner, so I'll follow that discussion and only use my module for my own use for the time being.

**Comment by sophof** [comment]
So it looks like that PR has been merged for Leia. I suppose I should update this PR to target Leia as well and wait for it to be released before submitting any plugin using the module?

**Comment by Razzeee** [comment]
You can submit a plugin as long as it's also targeting Leia. Nighlies are already available.

**Pull request closed without merging**
