### PR TITLE
[script.module.pycaption] 0.5.5

### PR DESCRIPTION
**Pull request by emilsvennesson**
I think this module will be useful for a lot of video plugins.
https://github.com/pbs/pycaption

### CODE REVIEW

**Comment by learningit** [comment]
Are there any addons using this module? We only include modules which addons make use of.

**Comment by emilsvennesson** [comment]
I'm using it in my plugin (https://github.com/emilsvennesson/kodi-viaplay) which I am planning to submit to the official repo once it's reasonably stable.

**Comment by learningit** [comment]
OK. We'll hold off including until then. Frankly I've found the module to be overkill for what needs to be done on the actual PBS content.

**Comment by emilsvennesson** [comment]
Fair enough. Should I just reference to this pull request once I've submitted my addon?

**Comment by learningit** [comment]
Yes. I would encourage you to think about writing 5 lines of code to eliminate the module, assuming you're doing a .vtt to .srt translate.

**Comment by emilsvennesson** [comment]
Unfortunately, I have to do a .sami to .srt which can be a pain in the ass. :/

**Comment by learningit** [comment]
I thought .smi files were supported by the player, at least they used to be...

**Comment by emilsvennesson** [comment]
And this just reminded me why you should always read the documentation... :see_no_evil:

**Pull request closed without merging**
