### PR TITLE
[script.module.youtube.dl@matrix] 23.04.01+matrix.1

### PR DESCRIPTION
**Pull request by joaopa00**
### Description
Update to the Git version of 01/04/2023 of youtube-dl
### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

### CODE REVIEW

**Comment by joaopa00** [comment]
Is it possible to have a feedback for this PR?

Thanks in advance.

**Comment by joaopa00** [comment]
Any feedback would be welcome. Thanks in advance

**Comment by romanvm** [comment]
Sorry for a very late reply. I finally have some spare time to clean our backlog. I'd like to know where the code was taken from. The PR is very big and reviewing it will take some time. However, if the code has some authoritative source, like popular Python libraries, I can just compare file hashes that will speed-up the process significantly.

**Comment by joaopa00** [comment]
Yes,  this plugin is just a wrapper for Kodi for the very-well known software youtube-dl [youtubedl](https://github.com/ytdl-org/youtube-dl)

This plugin wraps all the extractors of youtube-dl in a plugin usable by Kodi. Obviuously all the extractors can fetch legally  available video links only. Video link needing paying subscriptions can not be downloaded by youtube-dl (oyr you have to pay the video website to know what the link is).

Thanks for the review. Youtube changed its api very lon ago. Catchuptvandmore can not read youtube link now. So many video can not be played by catchuptvandmore now,.

**Comment by romanvm** [comment]
@joaopa00 Images addon is merged.

Regarding this addon, could you point me to the exact tag or commit in the upstream repo that this PR is based on? Because the latest tag there is [2021.12.17](https://github.com/ytdl-org/youtube-dl/releases/tag/2021.12.17) and the PR description above says "01/04/2023". Personally, I don't expect anything fishy in this PR but I want to do due diligence and at least compare MD5s.

**Comment by joaopa00** [comment]
This PR is based on GIT dated of April 1 2023.
From what I understood Youtube-dl did not released new stable version because some problems with cross-compiling on some platforms . There is no such problem for Kodi since we use only extractor that are python written.
[no new release for Youtube-dl](https://github.com/ytdl-org/youtube-dl/issues/31585)

**Review by romanvm — APPROVED** [review]
LGTM

**Comment by romanvm** [comment]
@joaopa00 Next time please note the commit in the youtube-dl repo that your PR is based on. It will speed up the process significantly. Thanks in advance.

**Pull request merged**
