### PR TITLE
[script.check.theme] 0.0.2

### PR DESCRIPTION
**Pull request by manfeed**
### Description

Script for skinners to check if a mp3 theme exists in a folder movie / tvshow.
Not sure if this is the right way to submit this addon in order to be admitted to the Matrix repository, please forgive my mistakes.

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

*** Here is the file ***
[script.check.theme.zip](https://github.com/xbmc/repo-scripts/files/4930252/script.check.theme.zip)

### CODE REVIEW

**Comment by enen92** [comment]
@manfeed your pr is invalid :)

**Comment by manfeed** [comment]
Well, I took that for granted :-)
Thing is that I don't even know Python, this is a little script that I need for my skin Aeon Tajo, and some time ago @ronie was so kind to write it for me and add it to Leia repository. Now I'm adapting my skin to Matrix and I need the script again in Matrix repository. Someone adapted it for me to Python 3 and provided me the new code, but I've been told that I'm the one that must ask for the PR... 
I don't have a clue about the conflicts you mention, so it seems that I'm at a dead end... 
If someone can help me with this, I will be able to keep adapting my skin, otherwise I will have to give up. Thanks!

**Comment by enen92** [comment]
@ronie can you help here?

**Comment by ronie** [comment]
> @ronie can you help here?

sorry but i have no idea what went wrong with this pr.
there are instructions in the wiki (https://kodi.wiki/view/HOW-TO:Create_add-on_PRs_using_Git_Subtree_Merging), but as i don't understand half of it myself, there's little help i can offer.

i did my best trying to convince everyone it's not a good idea to disable python addon submissions through an issue ticket, but it didn't work. i'll leave it up them to figure out how to best deal with developers who struggle with PR's.

**Comment by manfeed** [comment]
I've uploaded to github in case it helps...

https://github.com/manfeed/script.check.theme

**Comment by sarbes** [comment]
You've tried merging the Matrix branch into Master. You don't have a own fork to commit to our repo. Do the following steps:
- Fork the repository in GH
- Clone YOUR fork
- Add the files to your local clone and commit the changes
- Push your changes
- Make a PR from GH into the Matrix branch of our repo.

**Pull request closed without merging**
