### PR TITLE
[script.module.protobuf] 4.23.2

### PR DESCRIPTION
**Pull request by sanzoghenzo**
### Description

Re-introducing protobuf module for Kodi nexus.

I've done this to be able to revive the [hyperion add-on](https://github.com/hyperion-project/hyperion.kodi/pull/46) - if there's no activity there, I will do a PR personally.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

### CODE REVIEW

**Comment by basrieter** [comment]
Please make the add-on checker happy so we review.

**Comment by sanzoghenzo** [comment]
I'm sorry for the waiting, I was on vacation away from my PC.

Now it should be ok

**Comment by sanzoghenzo** [comment]
Should I do anything else to get this moving?

**Comment by sanzoghenzo** [comment]
@basrieter can you please advise if I have to do anything else or if it is ok?

**Comment by basrieter** [comment]
We will have to find some time to review it. But as this is a new submission, that might take some time. 

Besides that: what add-on/script is using this module?

**Comment by sanzoghenzo** [comment]
Thanks for the reply.
As stated in the OP, it is needed by the hyperion addon;
I'm waiting for someone to pick my PR on the official repo, but if I have no feedback in a few days I will submit it to you myself.

**Review by romanvm — APPROVED** [review]

**Pull request merged**
