### PR TITLE
[script.module.kodi-six] 0.1.0

### PR DESCRIPTION
**Pull request by romanvm**
### Add-on details:

- **General**
  - Add-on name: Kodi Six
  - Add-on ID: script.module.kodi-six
  - Version number: 0.1.0
  - Kodi/repository version: gotham

- **Code location**
  - URL: https://https://github.com/romanvm/kodi.six
  
Wrappers around Kodi Python API that normalize handling of textual and byte strings in Python 2 and 3.

### Description of changes:

0.1.0:
- Implemented lazy patching of Kodi API functions and classes.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by romanvm** [comment]
Since this version includes important performance optimization, I decided to push it to `gotham` as well.

**Comment by Rechi** [comment]
@romanvm Are you sure that you want to release this as version `0.1.0` too. So you never know which version one actually has.
Also keep in mind that it is not guaranteed that the Leia version is published to the Leia and higher repos in this case.

**Comment by romanvm** [comment]
I want to publish this version in all branches that are still open for updates because it includes an important performance fix, especially for less performant platforms like Pi.
What is the best way to do it? Maybe assign lower version number than in Leia but higher than here, e.g. 0.0.5?

**Comment by Rechi** [comment]
Everything higher then `0.0.2` and lower then `0.1.0` is fine. To be able to exactly identify the used version I wouldn't use `0.0.3` as that was already used in Leia branch.

**Comment by romanvm** [comment]
Ok, thanks. Then I'm closing this PR and will create a new one.

**Pull request closed without merging**
