### PR TITLE
[script.module.iso8601] 0.1.11

### PR DESCRIPTION
**Pull request by emilsvennesson**

### CODE REVIEW

**Comment by learningit** [comment]
At first glance, there's an issue with a new submission in the Gotham repo. New submissions are for Jarvis and above. script.module.m3u8 is in Helix, so there may be a case for putting script.module.iso8601 there.  If script.module.m3u8 is the only thing using it, why not just add as a lib folder?
Haven't looked at anything else yet.

**Comment by emilsvennesson** [comment]
@learningit: Oh, I didn't know about the submission issues. I expected this to work on all versions that weren't listed as deprecated (http://kodi.wiki/view/addon.xml) so that's why I submitted it to Gotham. I could re-do it and use the Helix branch instead if you want.

Wouldn't it make more sense to have iso8601 as a separate module? If we're still going to download the library, I think it'd be nice to let other addons use iso8601. I know I could use it in https://github.com/emilsvennesson/kodi-viaplay for example and possibly get rid of the heavy handed dateutil.parser approach.

**Comment by learningit** [comment]
Let me look through this, I have limited time today.  I would propose that iso8601 be added to Helix to be in line with the m3u8 module, but I want to make sure there won't be compatibility/upgrade issues for existing m3u8 module users. Give me a day or two to get back. Thanks.

**Comment by learningit** [comment]
BTW the repo submission matrix is in a different place: http://kodi.wiki/view/Submitting_Add-ons
Just to keep things confused.

**Comment by emilsvennesson** [comment]
@learningit Of course! Take your time. :-)

**Comment by learningit** [comment]
Finally got some time to test, the code seems fine and doesn't seem to have problems with other add-ons that use the m3u8 module. Please close this PR and re-submit into Helix. I will merge this and PR#226 into the Helix repo when that is done. Thanks.

**Comment by emilsvennesson** [comment]
@learningit Great! Thanks a lot. The new PR is at #249. :-)

**Pull request closed without merging**
