### PR TITLE
[script.xbmcbackup] 1.1.0

### PR DESCRIPTION
**Pull request by robweber**
### Description
From changelog, a summary of fixes: 

- fixed error on authorizers (missing secret/key)
- added ability to "catchup" on missed scheduled backup
- updated google oauth and client versions
- merged in dropbox v2 code
- added tinyurl for oauth urls
- moved authorize to settings area for cloud storage
- bug fixes

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by robweber** [comment]
Sorry for the additional commit. During testing I realized two imports were removed during some branch merges.

**Comment by mbelang** [comment]
@robweber This issue is also happening in krypton. Is it possible that you do a PR for it as well?

**Comment by robweber** [comment]
I was under the impression that Kodi addons for lesser versions automatically pushed to newer ones, ie Isengard addons worked on Jarvis and Krypton; Jarvis addons work on Krypton, etc. 

If that isn't right I can do a separate PR, I just didn't think it was necessary.

**Comment by Razzeee** [comment]
@robweber your right, as long as isengard has a version with a higher version number then jarvis or krypton (none is also okay)

**Comment by robweber** [comment]
Everything should be good then. I haven't ever pushed a version of this addon higher than Jarvis. Working on one with Krypton specific Kodi python lib changes but nothing to the repo just yet.

**Comment by mbelang** [comment]
@robweber Cool, I didn't know the procedure. It updated automatically and didn't realized it.

**Pull request merged**
