### PR TITLE
Add addon-check as submodule and setup travis-ci

### PR DESCRIPTION
**Pull request by Razzeee**

### CODE REVIEW

**Comment by Razzeee** [comment]
This one actually found broken png and dies on it. Not sure how to handle that.

**Comment by MartijnKaijser** [comment]
Ping the author?

**Comment by Razzeee** [comment]
I've prepared the needed fix for the test suite. But we should probably
also ping the author.

**Comment by Razzeee** [comment]
Authors email address isn't valid (anymore). So what are we going to do? Check if it works? Mark as broken?

**Comment by Rechi** [comment]
replace it with https://github.com/xbmc/repo-scripts/blob/dc0fbe652559859daaee41278d4ac5ee4f26eef1/script.service.radiovis/icon.png

**Pull request merged**
