### PR TITLE
[script.module.metahandler] 3.0.3

### PR DESCRIPTION
**Pull request by jsergio123**
@Lunatixz It will take some time to clean up all the code. I will work on it at a later time.
### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by Lunatixz** [comment]
Thanks for the PR, After reviewing the changes I'm confused to why this update was needed and why you couldn't use the metahandler currently in Kodis repository? Minor changes were added that do not affect the overall function of the module.. Yes metahandlers api key was suspended, however there was already a method for inputting your own api key...

**Comment by Lunatixz** [comment]
Also you should be aware there is a strong chance @Eldorados account was hijacked. I do not believe he is maintaining it; as I believe you already know....

**Comment by jsergio123** [comment]
You're obviously not familiar with this module because if you were you would realize it is broken. I have made many changes and fixes to this script that includes fixes for the duration being stored, incorrect movies/shows being returned, domain and api key changes for omdbapi.com. I also gave the user the option to set all their own keys for tvdb, tmdb, and omdb in the settings. I also allow users to override any tmdb api key passed to the script via an addon with their own key to workaround suspended/removed keys. There are a few other things I am forgetting.

I told you previously all the commits were lost when Eldorado deleted his repo. Also Eldorado's github hasn't been hijacked but now I see why him and many other developers avoid trying to work with Kodi and just choose 3rd party repositories instead. No offense.

**Comment by Lunatixz** [comment]
Im sorry if I missed something; I'll review again. However on my initial review I did not see the changes you described when comparing with the currently available version. Possible I missed something? I'm extremely experienced with this module and it's code so no need to concern yourself. If I overlooked modifications beyond API key something we can get this merged. :)

**Comment by Lunatixz** [comment]
I thoroughly reviewed the code and I stand by my intal conclusion; Sorry.

**Comment by jsergio123** [comment]
You're a moron...

**Comment by jsergio123** [comment]
@Lunatixz since you want to come on my Twitter, cry to me, and then block me; I'll post the changes here for everyone to see since you obliviously didn't look.

Tell me again how I didn't fix anything in the current version hosted by Kodi? You're welcome for the fixes and new keys to resurrect this dead module.

line# 1525 hxxps://www.diffchecker.com/jNINwfY4
line# 37 hxxps://www.diffchecker.com/kdBgj5DN
line# 31 hxxps://www.diffchecker.com/N9Gqf6N4
line# ?? hxxps://www.diffchecker.com/AJ2qiJgi

**Comment by Lunatixz** [comment]
https://twitter.com/jsergio123/status/966155550630166528

**Comment by jsergio123** [comment]
Excuse me for being frustrated from your bullsh* that which has been almost a week now. You still can't even admit you're  wrong.

**Comment by romanvm** [comment]
I'm not familiar with this addon specifically, but from the functionality POW I also don't see any changes beyond API key handling and correcting deprecated syntax of exception assignment.

**Comment by MartijnKaijser** [comment]
@jsergio123 if you cannot behave you better leave

**Comment by jsergio123** [comment]
@MartijnKaijser I really am trying but this is getting ridiculous with @Lunatixz. I dont even care if this PR gets merged. I'm bending over backwards for him just to get the adultswim plugin merged to the Kodi repo. I have other plugins as well that I would like to submit too.

@romanvm I see my domain and duration fixes were already committed by someone else but what about where I handle the incorrect tvshow's being matched and returned for shows that have the same title from different years? Also I guess you like sending thousands of denied requests to omdbapi.com. I'm sure Brian over at omdbapi.com loves it. Also that omdbapi key was donated from a member of 3rd party scene and is a paid patron pro subscription($10/mo).

**Comment by Eldorados** [comment]
No hijacking of my account, all is good just busy with real life's

I'm also confused by not accepting the update as the currently hosted version is at least 2-3 years old, changes since then were not submitted but are numerous, mainly as @jsergio123 pointed out those to the omdp api including a new key

Also allowing the user to input their own keys is a nice feature akin to the youtube addon

Regardless if the changes are big or small, if the developer feels it's important to have these fixes pushed out why is he being blocked from doing so? There's nothing malicious included, it's a useful script in need of an official update. I don't see any logical reasoning for rejecting it

**Comment by Eldorados** [comment]
One would think the inclusion of the omdb api key would be enough?

**Comment by Lunatixz** [comment]
If the changes are numerous then were are they? I can only review the code changes submitted. Look for yourself; you cannot tell me they are numerous.

As for what warrents a update; after the tmdb key issues hardcoded keys aren't recommend, nor are borrowed premium keys.

The bases of this commit was due to the instance by developer that his changes were required for a plug-in. On review I do not agree.

It should be noted that GitHub usernames are not secure and it's possible @eldoridos username was hijacked. If you'd like to discuss further we can do so on the Kodi forums. Thanks

**Comment by Eldorados** [comment]
The line changes were given above, maybe numerous isn't the correct word to use as you could interpret that to mean there are MANY, but why does there have to be? There are more than simple syntax changes as was implied

Short run down of what I see:
- Removing an old invalid tmdb api key should be enough to warrant the update, it was causing MANY invalid requests to TMDB which I'm sure they would be happy to be without, some addon dev's were using it without supplying their own keys
- Allowing user override of the tmdb and omdb api keys
- Bug fix for how the tv show result logic was being performed
https://www.diffchecker.com/jNINwfY4#left-48

- OMDB api url update (another bug fix)- https://www.diffchecker.com/kdBgj5DN

You did read thru the changes in those diff's right?

Hardcoding keys may not be recommended but it's not against the rules as I again use YouTube as a perfect example of an addon with it's own set of keys but allows user to override them

Recommendations is one thing, setting a rule to disallow is another. This does not sound like a rule, and it would be a rather ridiculous one if it was. The key was not stolen nor borrowed, it was given.

Also regardless of the reasoning to initiate the request, this is an update with bug fixes to an existing addon, if it's one line change or 100 it should not matter and I still haven't seen a valid reason for not allowing it.

I'll send you a pm on the forums to verify my identity

**Comment by Lunatixz** [comment]
@Eldorados 

I noted four additions,

1. Exceptions were updated to py3 compatible syntax.
2. Duration fix was nothing more than a try: except: pass around a calculation (Not exactly a fix; rather a poor patch).
3. User developer key option... "Key" word here "Developer keys" not user keys. Thanks to your forsite you already allow developers to input their own keys through python.
4. OMDB api was not properly added and includes hardcoded API which I already told him before the commit no hardcoded keys.

BTW the above additions only amount to maybe 10 lines of code and all patches... I can not in good faith allow random user to push updates to another developers code without it either being substantially updated or the original being completely broken... the two do not apply.

Rather then pick apart his submission I told him to use the older metahandler since there are no significant changes and its not broken...

**Comment by jsergio123** [comment]
@Lunatixz
1. I changed the exceptions to only appease you.
2. My duration fix was to convert seconds to minutes and nothing to do with a try/except.
3. I allow users to use all their own keys. Developers may still pass their keys too. Not just one key. The only key @Eldorados allowed to be passed was the TMDB key. There are 3 keys in total being used. TDMB, TVDB(already hardcoded by eldorado), and OMDB. Both TVDB and OMDB can not be passed or changed.
4. OMDB wasn't added by me and was always included in @Eldorados version. The current version doesn't even support an api key so all requests to the api are denied. You say no hard coded keys but the current version uses a hardcoded TVDB api key already.

Tell us all again how familiar you are with this script?

@Eldorados I only pushed this PR because @Lunatixz asked me to. He was fully aware of the situation and that I'm not some random user. The fact is I have only 2 options which is use this outdated module which is broken for my needs like I already explained to him or removed metadata from my adultswim addon completely because apparently I'm not even allowed to include my own metainfo script/module.

**Comment by Lunatixz** [comment]
**My request to remove apikeys**

> Lunatixz 4 days ago  •  edited  Member
> @jsergio123 I understand, why don't you push the metahandler update yourself. I'd advise removing default keys and documenting the need for individual developer keys.
https://github.com/xbmc/repo-plugins/pull/1672

**Hardcoded APIKEYS.**

`+<category label="TMDB (Movies)">
 +    <setting id="tmdb_language" label="Language" type="labelenum" default="English (en)" values="English (en)|Český (cs)|Dansk (da)|Deutsch (de)|ελληνικά (el)|Español (es)|Français (fr)|Magyar (hu)|Italiano (it)|Nederlands (nl)|Polski (pl)|Português (pt)|Pусский (ru)|Slovenščina (sk)|Svenska (sv)|Türkçe (tr)"/>
 +    <setting id="tmdb_poster_size" label="Poster Size" type="labelenum" default="w342" values="w92|w154|w185|w342|w500|original"/>
 +    <setting id="tmdb_backdrop_size" label="Backdrop Size" type="labelenum" default="original" values="w300|w780|w1280|original"/>
 +    <setting type="lsep" label="TMDB API Key" />
 +    <setting id="tmdb_api_key" type="text" label="Enter Your API Key" default="" option="hidden"/>
 +    <setting id="override_keys" type="bool" label="Override TMDB keys from all addons" default="False"/>
 +    <setting type="lsep" label="OMDB API Key" />
 +    <setting id="omdbapi_fallback" type="bool" label="Enable omdbapi.com Fallback" default="true"/>
 +    <setting id="omdb_api_key" type="text" label="Enter your API Key" default="f4adba76" option="hidden" enable="!eq(-1,false)"/>
 +</category>
 +<category label="TVDB (Series, Mangas and tvshows)">
 +    <setting id="tvdb_language" label="Language" type="labelenum" default="English (en)" values="English (en)|čeština (cs)|Dansk (da)|Deutsch (de)|ελληνικά (el)|Español (es)|Suomeksi (fi)|Français (fr)| עברית (he)|Hrvatski (hr)|Magyar (hu)|Italiano (it)|日本語 (ja)|Nederlands (nl)|Norsk (no)|Polski (pl)|Português (pt)|Pусский (ru)|Slovenski (sl)|Svenska (sv)|Türkçe (tr)|中文 (zh)"/>
 +    <setting type="lsep" label="TVDB API Key" />
 +    <setting id="tvdb_api_key" type="text" label="Enter Your API Key" default="2B8557E0CBF7D720" option="hidden"/>
 +</category>
 +</settings>`

**Comment by jsergio123** [comment]
@Lunatixz That's not a request. That's a suggestion.

**Pull request closed without merging**
