### PR TITLE
[script.module.websocket] v1.6.4

### PR DESCRIPTION
**Pull request by pkscout**
### Description

update websocket repack to current version

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

### CODE REVIEW

**Comment by pkscout** [comment]
I know this is two commits.  Every time I try and squash commits before merge, I mess something up.  So whoever reviews this, please just squash it at merge.  Thanks.

**Review by Dezzj — COMMENTED** [review]
Veiwed

**Comment by romanvm** [comment]
@pkscout Could you resolve the conflicts? I merged 1.6.2 version and it seems to have caused this.

**Comment by L2501** [comment]
@romanvm https://github.com/xbmc/repo-scripts/pull/2539

**Comment by romanvm** [comment]
Closing this since I merged #2539

**Pull request closed without merging**
