### PR TITLE
[script.myepisodes] 1.2.8: mark as broken

### PR DESCRIPTION
**Pull request by maximeh**
### Description
Mark addon as broken; a new version will be available for Krypton and up.
### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [script.foo.bar] v1.0.0

### CODE REVIEW

**Comment by Rechi** [comment]
@maximeh I also found versions in gotham and helix branch. I think those should be marked broken too.

**Comment by maximeh** [comment]
@Rechi okey will create a PR for each of them then.

**Comment by Rechi** [comment]
Bumping gotham branch to a higher version then helix would be enough, but it's up to you.

**Comment by maximeh** [comment]
@Rechi they would work with the new version of the addon ? I am wondering because of the dependencies.

**Comment by Rechi** [comment]
I don't get what you ask. If an addon is in gotham branch all it dependencies has to be available in that branches. If no higher version is available in a 'higher' branch the version from lower branch is used. Btw the version numbers listed in addon.xml are min versions, so they will always match in 'higher' branches.

See https://kodi.wiki/view/Submitting_Add-ons#Allowed_submissions and https://kodi.wiki/view/Addon.xml#version_attribute_2

**Comment by maximeh** [comment]
Agreed. But since the 2.0.0 version of my addon has min version for the dependencies that are only available in Krypton; it won't work if I bump the Gotham/Helix branch to use the 2.0.0 version of my addon; so I have no other choice than to mark them as broken.
Or did I misunderstood something ?

The current version of the addon is broken in gotham/helix so I can easily mark them as broken; but I can't easily upgrade them to the latest version.

**Comment by Rechi** [comment]
I meant something different, you only have to mark gotham version broken if you bump the version to a higher one then currently in the helix branch. That helix version will be automatically overwritten, as version has preference over branch where the addon is in.

**Comment by maximeh** [comment]
Ahhh ! I did not knew that.
Okey, that's indeed better only one PR to do instead of two :)
Thanks for the tips

**Pull request merged**
