### PR TITLE
[service.subtitles.subsfactory] 1.0.2

### PR DESCRIPTION
**Pull request by luivit**
hi, new version with several bugfix

### CODE REVIEW

**Comment by learningit** [comment]
A couple of things need to be done to review this:
please remove .gitattributes and .gitignore files from the commit.
At a glance, please do not use \__name\__ style labels, these should be reserved for python internals
Also please remove any print statements or replace with log - service.py has at least 1

**Comment by luivit** [comment]
Done it

**Comment by learningit** [comment]
Please squash your commits into 1 commit.
https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md

**Comment by luivit** [comment]
i'm sorry, i had forget :) 
now, should be ok

**Pull request merged**
