### PR TITLE
[script.module.jsbeautifier] 1.11.0.001

### PR DESCRIPTION
**Pull request by tingjhenjiang**
[script.module.jsbeautifier] 1.11.0.001
### Description
jsbeautifier ( [the original project is here](https://github.com/beautify-web/js-beautify) ) is a package for addon developers to parse javascript in requested html pages. With many media websites adopt more and more javascript to give users faster web site experience, and also many of them are using javascript obfuscators, jsbeautifier may be a nice tool to help them.

I packed essential parts of these projects releases (**source version is 1.11.0**) and make it a script.module addon to allow developers easily import them.
I have tested them in my own addon project built upon Kodi Leia.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by enen92** [comment]
Same concern as in the other pr:

- no module in the official repo is using it
- is that the upstream versioning?

**Comment by tingjhenjiang** [comment]
> Same concern as in the other pr:
> 
> * no module in the official repo is using it

The existence of script.module is to make potential project to appear. Not to mention I might publish my project which using this package.
What is the reason that new packages should be discriminated?

> * is that the upstream versioning?

I have mentioned that in the top post: this package tracks jsbeautifer 1.11.0 and the link to original github project page shows that it is the current release version.

**Comment by enen92** [comment]
If the script module targets jsbeautifier 1.11.0 please use the same version in the addon id so that we can track to which upstream version it refers to.

As for the other part of your comment, rule is that this can only be merged once an addon (in our repo) requires it.

**Comment by enen92** [comment]
Closing as no activity has been seen in a while. As said, modules need main add-ons that actually use them. Please resubmit if the interest persists

**Pull request closed without merging**
