### PR TITLE
[script.wadeysay] 0.0.11

### PR DESCRIPTION
**Pull request by icr8ions**
### Description
**What Did They Say?**
This addon will rewind the video and play it with subtitles.  Use it when you could not hear or understand what was just said. How much to rewind and which subtitle is selected is configurable.
NOTE: use Keymap Editor to map desired input or edit keymap file (fullscreenvideo -> runaddon)

Add-on name: **wadeysay**
Add-on ID: script.wadeysay
Version number: 0.0.11
Kodi/repository version: matrix

[SUPPORT](https://forum.kodi.tv/showthread.php?tid=372702)

### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

### CODE REVIEW

**Comment by icr8ions** [comment]
I believe all errors have been corrected.  Kindly trigger Kodi Addon-Checker again.

**Comment by icr8ions** [comment]
Will this warning block submission?
WARN: Complex entry point. Check: wadeysay.py | Counted lines: 25 | Lines allowed: 15

**Comment by icr8ions** [comment]
I think that push should do it...  Kindly trigger Kodi Addon-Checker again.

**Review by Lunatixz — CHANGES_REQUESTED** [review]
Plugin art can not be transparent. Looks like your icon is okay, but the fanart needs correction... Other than that it LGTM =)

**Comment by icr8ions** [comment]
@Lunatixz - Thank you for running the Kodi Addon-Checker again.

I made the fanart to be as unobtrusive as possible thus transparent such that the skin background could be seen.  I did follow the instructions for Add-on structure.  In the case of fanart it does not preclude transparency.

Here is what I followed: [https://kodi.wiki/view/Add-on_structure#fanart_specifications](https://kodi.wiki/view/Add-on_structure#fanart_specifications)
Screen Shot 2023-04-04 at 10 01 56 AM

Screenshots of fanart in addon with two different skins:
Screen Shot 2023-04-04 at 9 45 59 AM
screen

**Comment by Lunatixz** [comment]
> @Lunatixz - Thank you for running the Kodi Addon-Checker again.
> 
> I made the fanart to be as unobtrusive as possible thus transparent such that the skin background could be seen. I did follow the instructions for Add-on structure. In the case of fanart it does not preclude transparency.
> 
> Here is what I followed: https://kodi.wiki/view/Add-on_structure#fanart_specifications Screen Shot 2023-04-04 at 10 01 56 AM
> 
> Screenshots of fanart in addon with two different skins: Screen Shot 2023-04-04 at 9 45 59 AM screen

I can assure you transparent artwork (icons/fanart) are not allowed in the repository. Please make the changes and we are good to merge. The wiki needs updating... THX

**Comment by icr8ions** [comment]
done.

**Review by Lunatixz — APPROVED** [review]

**Comment by icr8ions** [comment]
@Lunatixz - what am I supposed to do now?
asking because of 'waiting for developer to respond' label...

**Pull request merged**
