### PR TITLE
[screensaver.digitalclock] 5.0.4

### PR DESCRIPTION
**Pull request by vdb86**
Added support for skins Ftv, Grid, Horizon and Reestuarized

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [script.foo.bar] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by vdb86** [comment]
I've got an additional question!
@ronie @samnazarko told me that there's a way of scripts defining their own fonts and he was supposed to send you a pull request with that code (if it can be submitted upstream) which would make lives of some of the addon developers (me included) a lot easier, that way we don't have to chase skin developers around and beg them to add something to their Font.xml
Is there any chance we could have that? :)

**Comment by MartijnKaijser** [comment]
He's wrong and we haven't seen any patch from yet. The patch was initially done by ronie who said it didn't work at all and wouldn't be accepted probably

**Comment by samnazarko** [comment]
I didn't realise ronie was working on this, so we can leave our implementation. It's useful for us for example having My OSMC look the same on all skins.

You have to use ```<fontset id="Default">``` in an add-on specific Font.xml for this to work as expected. But that may introduce security vulnerabilities if an add-on can load its own fonts

**Comment by MartijnKaijser** [comment]
no one is working in this. So if you want it you submit a PR.

**Pull request merged**
