### PR TITLE
[script.module.tzlocal] 3.0.0+matrix.1

### PR DESCRIPTION
**Pull request by finkleandeinhorn**
### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by razzeee** [comment]
LGTM

**Review by ronie — APPROVED** [review]

**Comment by sbroenne** [comment]
Unfortunately, there is an issue with this PR for systems with Python versions 3.6 to 3.8:

"It requires Python 3.6 or later, and **will use the backports.tzinfo package, for Python 3.6 to 3.8.**"

The module does not declare a dependency on [backports.tzinfo](https://pypi.org/project/backports.zoneinfo/) nor can I find such a module in the matrix repo. This causes all plugins that uses tzlocal and do not run on a system with Python 3.9 to fail.

**Comment by sy6sy2** [comment]
Agree with @sbroenne, Catch-UP TV & More add-on that use tzlocal does not work anymore since this update. (see https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/592).

This is the error:

```
2021-12-22 13:16:31.396 T:71449   ERROR <general>: [Catch-up-TV-&-More.support] 'unable to import route module: resources.lib.iptvmanager'
                                                   Traceback (most recent call last):
                                                     File "/Users/sylvain/Library/Application Support/Kodi/addons/script.module.codequick/lib/codequick/support.py", line 248, in get_route
                                                       importlib.import_module(module_path)
                                                     File "/Applications/Kodi.app/Contents/Libraries/lib/python3.8/importlib/__init__.py", line 127, in import_module
                                                       return _bootstrap._gcd_import(name[level:], package, level)
                                                     File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
                                                     File "<frozen importlib._bootstrap>", line 991, in _find_and_load
                                                     File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
                                                     File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
                                                     File "<frozen importlib._bootstrap_external>", line 783, in exec_module
                                                     File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
                                                     File "/Users/sylvain/Library/Application Support/Kodi/addons/plugin.video.catchuptvandmore/resources/lib/iptvmanager.py", line 17, in <module>
                                                       from resources.lib.xmltv import grab_programmes
                                                     File "/Users/sylvain/Library/Application Support/Kodi/addons/plugin.video.catchuptvandmore/resources/lib/xmltv.py", line 26, in <module>
                                                       from tzlocal import get_localzone
                                                     File "/Users/sylvain/Library/Application Support/Kodi/addons/script.module.tzlocal/lib/tzlocal/__init__.py", line 5, in <module>
                                                       from tzlocal.unix import get_localzone, reload_localzone
                                                     File "/Users/sylvain/Library/Application Support/Kodi/addons/script.module.tzlocal/lib/tzlocal/unix.py", line 12, in <module>
                                                       from backports.zoneinfo import ZoneInfo, ZoneInfoNotFoundError
                                                   ModuleNotFoundError: No module named 'backports'
```

**Comment by ronie** [comment]
@sbroenne @sy6sy2 could you please install these two updates and let me know if it fixes the issue:
[script.module.backports.zoneinfo-0.2.1+matrix.1.zip](https://github.com/ronie/repo-scripts/releases/download/foo/script.module.backports.zoneinfo-0.2.1+matrix.1.zip)
[script.module.tzlocal-3.0.0+matrix.2.zip](https://github.com/ronie/repo-scripts/releases/download/foo/script.module.tzlocal-3.0.0+matrix.2.zip)

**Comment by sbroenne** [comment]
@ronie, unfortunately it is still not fixed (at least on Windows) - backports-zoneinfo seems to require [tzdata](https://pypi.org/project/tzdata/) to work. Haven't tested it on any other platform.

This is what I see in kodi.log:  ModuleNotFoundError: No module named 'tzdata'

Quick verfication of the "fix": I have manually copied the tzdata module to *\Kodi\system\Python\Lib* and then everything works.

**Comment by ronie** [comment]
thanx for testing the updates!

i've created PR's which also includes the missing tzdata module:

https://github.com/xbmc/repo-scripts/pull/2173
https://github.com/xbmc/repo-scripts/pull/2172
https://github.com/xbmc/repo-scripts/pull/2171

**Pull request merged**
