### PR TITLE
[service.xbmc.versioncheck] v0.5.7

### PR DESCRIPTION
**Pull request by anxdpanic**
### Description

add Kodi 19.0 alpha2 release
### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Review by enen92 — APPROVED** [review]

**Comment by KarellenX** [comment]
My Kodi tried to update with this new version and it fails.

Error is...

```xml
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
             Error Type: <type 'exceptions.AttributeError'>
             Error Contents: 'tuple' object has no attribute 'system'
             Traceback (most recent call last):
                  File "C:\Users\Master\AppData\Roaming\Kodi\addons\service.xbmc.versioncheck\resources\lib\runner.py", line 14, in <module>
                  from version_check import service  # pylint: disable=import-error
                  File "C:\Users\Master\AppData\Roaming\Kodi\addons\service.xbmc.versioncheck\resources\lib\version_check\service.py", line 50, in <module>
                       DISTRIBUTION = platform.uname().system.lower()
             AttributeError: 'tuple' object has no attribute 'system'
             -->End of Python script error report<--
DEBUG: CPythonInvoker::onExecutionDone(0, C:\Users\Master\AppData\Roaming\Kodi\addons\service.xbmc.versioncheck\resources\lib\runner.py)
```

**Comment by ronie** [comment]
reported on the forum as well:
https://forum.kodi.tv/showthread.php?tid=357540

**Comment by anxdpanic** [comment]
Of course I'd forget to change that after moving it out of the python 3 area. thanks for the heads up 👍  fixup is pr'd.

**Comment by ShibajiCh** [comment]
Suddenly today I started getting Version Check Error every time I start Kodi.
I'm running Kodi on Amazon Fire Stick 4K with Arctic Zephyr 2 skin.
Please advise.

Here is my log:

ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'tuple' object has no attribute 'system'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/service.xbmc.versioncheck/resources/lib/runner.py", line 14, in <module>
                                                from version_check import service  # pylint: disable=import-error
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/service.xbmc.versioncheck/resources/lib/version_check/service.py", line 50, in <module>
                                                DISTRIBUTION = platform.uname().system.lower()
                                            AttributeError: 'tuple' object has no attribute 'system'
                                            -->End of Python script error report<--

**Pull request merged**
