### PR TITLE
[script.black.bars.never] 1.0.11

### PR DESCRIPTION
**Pull request by osumoclement**
### Description
An addon to remove black bars automatically and reliably, even when hard coded

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by romanvm** [comment]
Please fix images according to the addon checker log.

**Comment by osumoclement** [comment]
Hello, I have fixed the images

**Comment by osumoclement** [comment]
What does screenshot-01.jpg is marked as stand-alone executable mean?

**Comment by romanvm** [comment]
> What does screenshot-01.jpg is marked as stand-alone executable mean?

If you are on a *nix based system, then it probably has executable flag.

**Comment by osumoclement** [comment]
Fixed the executable flag

**Review by romanvm — APPROVED** [review]
LGTM

**Pull request merged**
