### PR TITLE
[script.colorbox] 1.0.9

### PR DESCRIPTION
**Pull request by BADMS**
Right, as there was never a version 1.0.8 in repo and as 1.0.7 is latest, I will revert version to 1.0.9 as it will make zero difference to kodi users. This hopefully fixes erronious version 1.0.10 issues with the 1.0.9 commits (!).
Hope this is ok.

Greets!

### CODE REVIEW

**Comment by learningit** [comment]
Please look at my comments on the PR you closed. You now have 3 commits in this PR. Please either pick or squash which commit(s) you want in the PR and submit a PR with a single commit in it. I gave you a link for how to do that in my comments on the PR you closed.

**Comment by BADMS** [comment]
eh? it has 3 PR as i edited addon.xml to version 1.0.9.
Is this really a big issue?
Are you saying you dont want to see my commits in the PR?!

**Comment by MartijnKaijser** [comment]
Correct. We only want a single commit

**Comment by BADMS** [comment]
ok.. sorry will fix!

**Pull request closed without merging**
