### PR TITLE
[script.module.enum34] 1.1.6

### PR DESCRIPTION
**Pull request by jmooremcc**
### Description

An enumeration is a set of symbolic names (members) bound to unique, constant values
This module is the backported version of the enum34 package that runs under Python 2.7

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by basrieter** [comment]
@jmooremcc did you see the comment on the missing files?

**Comment by jmooremcc** [comment]
> @jmooremcc did you see the comment on the missing files?

I'm sorry, I didn't see the comment until today.
I'll fix the problem within the next 30 minutes .

Thank you for your help and your patience.

**Comment by jmooremcc** [comment]
I have no idea what's behind the Travis Buddy failed check. It's the same code that previously passed the checks with the exception of the enum directory being renamed enum34.

**Comment by jmooremcc** [comment]
> Looks good to me. We need an approved add-on that uses this before we merge.

My add-on, PR #1172 Live TV Playlist, requires this add-on.

**Comment by enen92** [comment]
Closing as no activity for a while

**Pull request closed without merging**
