### PR TITLE
[script.module.beautifulsoup] 3.2.2+matrix.1

### PR DESCRIPTION
**Pull request by zoreu**
### Description
 - Beautiful soup in version 3.2.2 for the Kodi matrix
 - this module was converted from python2 to python3
- Documentation: https://www.crummy.com/software/BeautifulSoup/bs3/documentation.html

### Checklist:

- [x] My code follows the add-on rules and piracy stance of this project.

- [x] I have read the CONTRIBUTING document

- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by enen92** [comment]
Why do you need this. We have beautifulsoup in the matrix repo already: https://github.com/xbmc/repo-scripts/tree/matrix/script.module.beautifulsoup4

**Comment by zoreu** [comment]
> Why do you need this= We have beautifulsoup in the matrix repo already: https://github.com/xbmc/repo-scripts/tree/matrix/script.module.beautifulsoup4

@enen92 there are some things you don't get with beatifulsoap4

**Comment by enen92** [comment]
such as...

**Comment by zoreu** [comment]
> such as...

on beautifulsoap4, find does not find sub items of a <channel> in the xml file

**Comment by enen92** [comment]
I find that pretty hard to believe. Please post a snippet of your current code that only works with beautifulsoup3. Also, note that any modules added to the repo must be used by at least one addon in our official repo.

**Comment by zoreu** [comment]
> 
> 
> I find that pretty hard to believe. Please post a snippet of your current code that only works with beautifulsoup3. Also, note that any modules added to the repo must be used by at least one addon in our official repo.

Example, this code:
```
<channel>
<name></name>
<item>
<title></title>
<link></link>
<jsonrpc></jsonrpc>
<thumbnail></thumbnail>
<fanart></fanart>
<info></info>
</item>
</channel>
```
in beautifulsoap 3, I use: 
```
soup = BeautifulSOAP(data, convertEntities=BeautifulStoneSoup.XML_ENTITIES)
channel_list = soup.find('channel', attrs={'name' : name.decode('utf-8')})
```
to select the channel by name, and display the items for that channel, on beautifulsoap4 and show me just None

**Comment by enen92** [comment]
You're searching for an attribute of a xml tag when your xml elements don't have any attributes. You actually want to search for the text/value of a child node. Something like this works fine:

```
from bs4 import BeautifulSoup

xml_data = '''
<?xml version="1.0" encoding="ISO-8859-1"?>
  <channels>
    <channel>
        <name>bbc1</name>
        <item>
            <title></title>
            <link></link>
            <jsonrpc></jsonrpc>
            <thumbnail></thumbnail>
            <fanart></fanart>
            <info></info>
        </item>
   </channel>
   <channel>
        <name>bbc2</name>
        <item>
            <title></title>
            <link></link>
            <jsonrpc></jsonrpc>
            <thumbnail></thumbnail>
            <fanart></fanart>
            <info></info>
        </item>
    </channel>
  <channels>
'''

soup = BeautifulSoup(xml_data, 'xml')
channel_list = [item.parent for item in soup.findAll('name', text='bbc1')]
print(channel_list)
```

**Pull request closed without merging**
