### PR TITLE
[script.skinshortcuts] v1.1.3+matrix.1

### PR DESCRIPTION
**Pull request by CRialDev**
Update for Matrix -> Replace xbmc.translatePath by xbmcvfs.translatePath"
Update for Py3-> Change "is not" by "!="

### CODE REVIEW

**Comment by enen92** [comment]
@mikesilvo164 are you fine with these changes? Code doesn't seem to be in the upstream repo...

**Comment by mikesilvo164** [comment]
I actually had most of these changes locally. I just pushed those changes now. I will have to check this PR later as the GitHub website isn't working well, at the moment, for me.

**Comment by mikesilvo164** [comment]
What's with the +matrix.1 version number tho?

**Comment by mikesilvo164** [comment]
I do see some "is not" switched to "!=" on some lines...

**Comment by mikesilvo164** [comment]
Might be easier for me if this was closed and I just open a new PR instead.

**Comment by enen92** [comment]
Sure @mikesilvo164 please submit the update

**Pull request closed without merging**
