### PR TITLE
gTTS 2.0.4

### PR DESCRIPTION
**Pull request by YannBrrd**
No idea on how to test locally

### Description
Adding gTTS module
### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by Rechi** [comment]
@YannBrrd script.modules are only accepted into the repo if they are actually used by some add-on. Otherwise there isn't much use in adding them.

Please submit the add-on which requires this module. Once that one and the script.module are in a state to get accepted both will get merged at the same time.

**Comment by YannBrrd** [comment]
Hi Rechi,

The plugin to use oit is kinda private. Means I can"t have gTTS as a module ? What is my alternative ? Is there a way I kinda package it just for myself ?

**Comment by Rechi** [comment]
You can still use gTTS as module, it can be installed the same way as the add-on using it.

**Comment by YannBrrd** [comment]
Not sure I got you. Means I can just ûsh my gTTS module in my private repo ?

**Comment by Rechi** [comment]
Yes you can.

**Pull request closed without merging**
