### PR TITLE
[Xbmc-addons] [Git Pull] script.featherence.service

### PR DESCRIPTION
**Pull request by finalmakerr**
First time trying :)

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
It will never be accepted in current state. It contains a lot of reference to stuff which is banned. Start cleaning it up and reading the repo and forum rules

**Comment by MartijnKaijser** [comment]
Too add there absolutely no reason to include keymaps, samba configs, sources.xml files and blatend copies of already existing addons and whatever more.

**Comment by finalmakerr** [comment]
Will work it out np.
Thanks and sorry for your troubles.

**Comment by finalmakerr** [comment]
Martijn,
I removed the entire special folder and the relative modules and settings.xml
Now i am removing the reference for some addons.
Please if you could be so kind to direct me to some list of banned addons just to be sure.

P.S. I have readed the forum rules , will do so again soon.

**Pull request closed without merging**
