### PR TITLE
[script.tag-generator] 0.0.5

### PR DESCRIPTION
**Pull request by Razzeee**
@wellspokenman
https://github.com/xbmc/repo-scripts/issues/478

### CODE REVIEW

**Comment by Razzeee** [comment]
the trakt library used is another one, not the same

**Comment by wellspokenman** [comment]
- The icon doesn't have to change
- There is a good reason those modules are embedded. Requests, simplejson and oauth are required outside of Kodi by the included Trakt module. This is not the same as the Trakt addon - it does the oauth work now required after the changes to the Trakt API.

**Comment by Razzeee** [comment]
Here are some improvements, but it will need to target the krypton branch, as the dependencies are only available after that version.

Modules talking to inlined modules work fine btw. I haven't had or can remember any problems.

https://github.com/wellspokenman/tag-generator/pull/2

**Comment by Razzeee** [comment]
Should I update this to the newest version? And should it still be 0.5.0 then or would you do a new version  @wellspokenman ?

**Comment by wellspokenman** [comment]
@Razzeee I think 0.5.1 seems appropriate. No new features for the user, so a minor change. It seems that my skillset is inadequate for contributing to the main repo, so I'll refrain from doing so until I can address that. Thank you for bridging the gap.

**Comment by Razzeee** [comment]
Are you sure? I can arrage everything that's needed as it's only a new PR and a bump of the version :)

**Comment by wellspokenman** [comment]
I meant, yes please and thank you to doing this one (0.5.1) - we've both put in too much time to back out now. I just meant to say that I won't be doing this again until I can be more autonomous during submission.

**Pull request closed without merging**
