### PR TITLE
[script.playrandomvideos] 1.2.0

### PR DESCRIPTION
**Pull request by rmrector**
### Description
- Feature: merge in 'Play one random' context item
- Feature: option for continuous play
- Feature: option to play from all videos if no (un)watched videos available as configured
- Feature: option to exclude TV show extras from random selection
- Fix: Leia compatibility for context items

Originally in the Isengard repo. The previous version will continue to work fine, these are just additional tweaks to the results.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by enen92** [comment]
new addon submissions can only be submitted to krypton and above. Please adjust the pull request and the necessary info in addon.xml (python version)

**Comment by rmrector** [comment]
This is not a new add-on, it was previously in the Isengard repository. I will absolutely not break Jarvis compatibility just to submit a new version to the official repo.

**Comment by enen92** [comment]
Why don't you update the version in the isengard branch instead of submitting an update to the jarvis branch (which can't accept submission of new addons)? The fact the addon does not exist in the jarvis branch makes it a new submission and not an update.

**Comment by rmrector** [comment]
Because it has multiple context items, which Isengard doesn't support. It's time for me to drop Isengard support, but that doesn't mean I'm ready to leave Jarvis behind, there are still plenty of users. It's an update to an existing add-on, treating it as new makes it impossible for add-ons to keep support for the still-used previous version of Kodi while dropping much less used older versions. Add-on developers need to be able to support a shifting range of Kodi versions.

**Comment by MartijnKaijser** [comment]
let's not be too strict. I'd e ok with putting it in jarvis.

**Comment by enen92** [comment]
Thanks for having a look and give your opinion. I'll review this as a valid PR then.

**Comment by rmrector** [comment]
Thanks.

**Comment by Lunatixz** [comment]
BTW, LGTM... except for jarvis branch... which I guess is being reopened?

**Pull request merged**
