### PR TITLE
[script.artistslideshow] 3.2.0

### PR DESCRIPTION
**Pull request by pkscout**
### Description
v.3.2.0
- added option to pause slideshow when playback pauses
- logic change to load first slideshow image sooner
- override slideshow no longer resets at each song change
- fix for potential runaway loop
- fix for slow slideshow change when artist changes
- fix for AS not reloading settings properly when in daemon mode
- fixes for miscellaneous UTF8 errors
- internal change to the way the main thread talks to the slideshow thread

Note that once this one is cleared, I'll submit another to the Matrix branch with the updated python requirement and a higher version number (as per the forum post regarding this).

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by pkscout** [comment]
The XML validator seems to be failing on a spot where I pass two variables back to my addon via RunScript, and it appears the correct Kodi way to do that generates technically invalid but functional XML.  If there's a way to fix that, I'm all ears.

**Comment by anxdpanic** [comment]
@pkscout 
Would it work to change the `&` to `&amp;`  https://github.com/xbmc/repo-scripts/blob/cde3e6c0ebfb09379ca94d30e50391e393619b9f/script.artistslideshow/resources/settings.xml#L67 
as well as https://github.com/xbmc/repo-scripts/blob/cde3e6c0ebfb09379ca94d30e50391e393619b9f/script.artistslideshow/resources/lib/artistslideshow.py#L977 
to ```params = dict( arg.split( '=' ) for arg in sys.argv[ 1 ].replace( '&amp;', '&' ).split( '&' ) )``` ?

**Comment by enen92** [comment]
For me the change "&" to "&amp;" solves the issue, not sure if the addon code needs any further changes. Travis must pass before merging the PR so please test and adjust

**Comment by pkscout** [comment]
OK, I think I did this right. I pushed the changes to my fork and Travis reran with no errors. So my guess is you need to finish whatever code review and then squash this into one commit on your end (assuming there are no other changes).  I did have to bump the version number because the other version got pushed to my beta repo, so there are folks besides me who may have the bad code on their systems.

**Comment by pkscout** [comment]
Is there something else I need to do to get this merged into the main repo?

**Pull request merged**
