### PR TITLE
[plugin.video.npogemist] 1.1.0

### PR DESCRIPTION
**Pull request by dnicolaas**
### Description

Watch Dutch public broadcast television (NPO) on kodi. Only works if you have a Dutch IP address.

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [script.foo.bar] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by Rechi** [comment]
> This branch is not used for public. Please use one of the other branches available for submitting add-ons.

This is wrong branch and also the wrong repo. The correct repo is https://github.com/xbmc/repo-plugins and as this is a new add-on you can submit it either to krypton or leia branch.

**Comment by dnicolaas** [comment]
My apologies. I kind of literally followed the instructions here:
https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md
Maybe they should be revised?
I'll try again later.

Cheers
Dion

Op 12/21/2018 om 5:16 PM schreef Rechi:

**Comment by dnicolaas** [comment]
I'm trying to find out how to create a pull request against the krypton branch but that is not very clear to me. Can you advise me how to do that?Thanks in advance,Dion NicolaasOp 21 dec. 2018 6:48 p.m. schreef Dion Nicolaas <dion@nicolaas.net>:
    My apologies. I kind of literally followed the instructions here:
    https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md
    Maybe they should be revised?
    I'll try again later.
    
    Cheers
    Dion
    
    Op 12/21/2018 om 5:16 PM schreef Rechi:
    
    
      
      
        This branch is not used for public. Please use one of the
          other branches available for submitting add-ons.
      
      This is wrong branch and also the wrong repo. The correct repo
        is https://github.com/xbmc/repo-plugins
        and as this is a new add-on you can submit it either to krypton
        or leia branch.

**Comment by Rechi** [comment]
The following commands assumes that you have set up origin and upstream remotes as descried in CONTRIBUTING.md.

```
git checkout -b plugin.video.npogemist upstream/krypton
# or the following command if you already have a branch named plugin.video.npogemist
git reset --hard upstream/krypton
# copy the addon to plugin.video.npogemist subfolder
git add -- plugin.video.npogemist/
git commit -m '[plugin.video.npogemist] <VERSION>'
git push origin plugin.video.npogemist
```

So the first command is the one you are searching for. The others should be already familiar. Then you create a PR as usual but select krypton as target branch instead of master.

Just a reminder: you add-on has to be submitted to repo-plugins.

**Comment by dnicolaas** [comment]
Thanks, Rechi. I just created another pull request. I hope I got it right this time.Best regards,DionOp 21 dec. 2018 20:49 schreef Rechi <notifications@github.com>:The following commands assumes that you have set up origin and upstream remotes as descried in CONTRIBUTING.md.
git checkout -b plugin.video.npogemist upstream/krypton
# or the following command if you already have a branch named plugin.video.npogemist
git reset --hard upstream/krypton
# copy the addon to plugin.video.npogemist subfolder
git add -- plugin.video.npogemist/
git commit -m '[plugin.video.npogemist] <VERSION>'
git push origin plugin.video.npogemist

So the first command is the one you are searching for. The others should be already familiar. Then you create a PR as usual but select krypton as target branch instead of master.
Just a reminder: you add-on has to be submitted to repo-plugins.

**Pull request closed without merging**
