### PR TITLE
[script.artistslideshow] 2.1.4

### PR DESCRIPTION
**Pull request by pkscout**
### Description
v.2.1.4
- fix for fallback images not showing if all artists on a multi-artist song have no images

### Checklist:

- [ x ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ x ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [ x ] Each add-on submission should be a single commit with using the following style: [script.foo.bar] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by Rechi** [comment]
I think the following format is more useful to understand the error reported by addon-checker. (It is already implemented to report it that way for some time, but wasn't released yet.)
```
ERROR: ./script.artistslideshow/default.py
--- ./script.artistslideshow/default.py	(original)
+++ ./script.artistslideshow/default.py	(refactored)
@@ -188,7 +188,7 @@
                 time.sleep(1)
                 if self._get_infolabel( self.ARTISTSLIDESHOWRUNNING ) == "True":
                     if( xbmc.Player().isPlayingAudio() == True or self._get_infolabel( self.EXTERNALCALL ) != '' ):
-                        if set( self.ALLARTISTS ) <> set( self._get_current_artists() ):
+                        if set( self.ALLARTISTS ) != set( self._get_current_artists() ):
                             self._clear_properties()
                             self.UsingFallback = False
                             self._use_correct_artwork()
@@ -724,7 +724,7 @@
 
 
     def _playback_stopped_or_changed( self ):
-        if set( self.ALLARTISTS ) <> set( self._get_current_artists() ) or self.EXTERNALCALLSTATUS != self._get_infolabel( self.EXTERNALCALL ):
+        if set( self.ALLARTISTS ) != set( self._get_current_artists() ) or self.EXTERNALCALLSTATUS != self._get_infolabel( self.EXTERNALCALL ):
             self._clear_properties()
             return True
         else:
@@ -743,7 +743,7 @@
 
 
     def _remove_trailing_dot( self, thename ):
-        if thename[-1] == '.' and len( thename ) > 1 and self.ENDREPLACE <> '.':
+        if thename[-1] == '.' and len( thename ) > 1 and self.ENDREPLACE != '.':
             return self._remove_trailing_dot( thename[:-1] + self.ENDREPLACE )
         else:
             return thename
```

Also you have inconsistent use of tabs and spaces in indentation in 
script.artistslideshow/default.py on line 519 and 1253.

**Comment by pkscout** [comment]
Got it.  I'll fix those.  I think I need to do a new pull request then, right?  I'm using the Submit Kodi Addon app at https://submit-addon.netlify.com/ (super helpful BTW), and I don't see any way to update an existing PR using that.  I'll leave this one open for now and wait until I hear one way or the other before submitting another.  Thanks.

**Comment by Rechi** [comment]
I don't know that app, so I can't tell you if it's possible to update this PR with it.

**Comment by pkscout** [comment]
Honestly, my git skills are marginal at best.  I'm not seeing any easy way to update this, so I'm going to close this one and resubmit.  I think I may sign up for a Codacy account to see if I can do some of this automated testing *before* I submit and save us all some time.

**Pull request closed without merging**
