### PR TITLE
[script.skin.helper.colorpicker] 1.0.11

### PR DESCRIPTION
**Pull request by marcelveldt**
### Description
updated version - minor changes, mostly an attempt to work around the issues with PIL on atv4 and ftv.
### Checklist:
- [ X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [X ] Each add-on submission should be a single commit with using the following style: [sciprt.foo.bar] v1.0.0

### CODE REVIEW

**Comment by Razzeee** [comment]
Commit style is wrong

**Comment by marcelveldt** [comment]
Now better?

**Comment by Razzeee** [comment]
Nope, that only changes the title of the PR not the commits

**Comment by ronie** [comment]
code looks ok to me.

**Comment by marcelveldt** [comment]
I still have no idea what's wrong with this PR. Can you enlight me please ?

**Comment by Razzeee** [comment]
This: 
image
Should show `[script.skin.helper.colorpicker] 1.0.11`
All your other PRs also have this formatting wrong.

You can try `git commit --amend -m "[script.skin.helper.colorpicker] 1.0.11"` in your git repo (make sure there are no other changes around). Then force push.

**Pull request merged**
