### PR TITLE
[screensaver.isslive] 1.0.0

### PR DESCRIPTION
**Pull request by Lunatixz**
### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by Lunatixz** [comment]
@enen92 hmm I didn't know that... THX I'll make those changes.

**Comment by Lunatixz** [comment]
Hey @enen92 i'm not seeing the behavior you described. Log review shows the screensaver starts, then is shutdown properly after init of my script (as designed). Then termination of the screensaver is controlled by any user action. Did I miss something? THX

**Comment by Lunatixz** [comment]
@enen92 I'm reviewing your aerial screensaver and how you handle playback in order to avoid issues.

**Comment by enen92** [comment]
@Lunatixz it can occur sometimes unless something has changed on the kodi side. In fact all the video screensavers have the same type of logic since video screensavers are really a hack. The moment you start a video you trigger screensaver deactivate

**Comment by Lunatixz** [comment]
@enen92 yes I've observed that behavior, and kinda count on it...  using window onaction to deactivate the screensaver when it's time. Is that the issue? I've tried and reviewed various methods all seem to result in similar log events as the script already submitted. 

I'm trying to get a handle on the issue so that I can understand the problem... THX

**Pull request closed without merging**
