### PR TITLE
[screensaver.random] 1.2.0

### PR DESCRIPTION
**Pull request by robwebset**
Please can I have the following merged.

Changes:
- Add option to schedule different screensavers at different times

Thanks, Rob

### CODE REVIEW

**Comment by phil65** [comment]
looks good to me.
Why are your diffs always so polluted though? Do you change line endings back and forth?

**Comment by robwebset** [comment]
@phil65 It's something I'm changing to LF when each addon changes, it was requested here:

https://github.com/xbmc/repo-scripts/pull/122#issuecomment-216025273

I am just changing them as I update each addon - rather than doing a mass of updates in one go.

**Comment by phil65** [comment]
ok, thx for info.

**Comment by robwebset** [comment]
Thanks, Rob

**Pull request merged**
