### PR TITLE
[weather.ozweather@matrix] 2.0.0

### PR DESCRIPTION
**Pull request by bossanova808**
### Add-on details:

- **General**
  - Add-on name: Oz Weather
  - Add-on ID: weather.ozweather
  - Version number: 2.0.0
  - Kodi/repository version: matrix

- **Code location**
  - URL: https://github.com/bossanova808/weather.ozweather
  
Weather forecasting and radar images for Australia using Bureau of Meteorology data.  For full features (animated radars & ABC weather videos) - make sure you install the replacement skin files - see information at the addon wiki (https://kodi.wiki/index.php?title=Add-on:Oz_Weather).

### Description of changes:

V2.0.0
			- N.B. If you have run a version before 2.0, please re-configure the addon to set-up your new BOM locations
			- Rewrite to use BOM API directly, leave Weatherzone in as a fallback option. if BOM not configured or available
			- Auto-locate & configure nearest radar
			- Add mechanism to manually purge radar backgrounds via addon settings
			- Remove periodic refresh of backgrounds in favour of the above
			- Update settings.xml to new Kodi format
			- Modernise code throughout
    	

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by bossanova808** [comment]
Fixed a minor missing string issue and added auto-location of the radars.

**Comment by bossanova808** [comment]
I have pushed various little fixes and improvements given a review has not started yet...

**Comment by bossanova808** [comment]
Would really appreciate a review here.  The issue that kicked off this monster re-write was an upstream data source breaking change.  That issue appears to be getting worse, and folks are beginning to post messages on the Kodi forum about the breakage.

This new version is essentially a complete re-write to use a different data source, and modernise and improve code throughout.

@romanvm thanks for your time when you do get there!

**Review by romanvm — APPROVED** [review]
LGTM

**Pull request merged**
