### PR TITLE
[script.module.unmanic] 0.0.7~beta2

### PR DESCRIPTION
**Pull request by Josh5**
### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by basrieter** [comment]
Please fix the execution rights on the service.py

**Comment by basrieter** [comment]
Is identical to https://pypi.org/project/unmanic/0.0.7/ but that comes from the same author.

**Comment by Josh5** [comment]
> Is identical to https://pypi.org/project/unmanic/0.0.7/ but that comes from the same author, I do want to peak a bit through the code.

Source available here:
https://github.com/unmanic

**Comment by basrieter** [comment]
So the main question I have is this: why should all of this run inside Kodi? I can imagine that there could be a Kodi Client that connects to the main Unmanic app. But having Kodi host the complete thing including PHP seems odd. Kodi is not meant for that, it's a media player. 

Are there any options to take the whole webserver part outside of Kodi and create a lightweight component for Kodi?

**Comment by Josh5** [comment]
> So the main question I have is this: why should all of this run inside Kodi? I can imagine that there could be a Kodi Client that connects to the main Unmanic app. But having Kodi host the complete thing including PHP seems odd. Kodi is not meant for that, it's a media player. 
> 
> Are there any options to take the whole webserver part outside of Kodi and create a lightweight component for Kodi?

There is no PHP here. Perhaps a fair amount of bloated JavaScript. But I am working on removing a lot of the webui bloat.

I guess it's more for the libreelec sort of installations or Android. There is not really a way to run it on those systems.
I could look at making a separate Android app and opening a pr to the libreelec (and every other *elec is repo) for this, but I thought perhaps if I just add it to the official Kodi repo, then it's able to be used on all these systems.

If I were to remove these modules from the Kodi repos, there is absolutely still the option to have a lightweight Kodi plugin for sending data to Unmanic or for managing the Unmanic webui from Kodi, but I am not sure what the point of it is TBH. 
It's really hard to know what things will be used for with Kodi as Kodi itself is used in so many different ways. When I first released Unmanic, I had a set use case for it. But I soon started getting feedback that people were using it in ways I hadn't even considered.

In my mind, with this current PR, the only use for Unmanic is for the person who has a HDD or local collection of files that a single instance of Kodi looks at. I doubt this is useful to anyone who centralised their library on a NAS as Unmanic is already available to them to run on that NAS. And it's definitely not useful to anyone who streams content from the internet. Perhaps it's not worth creating a Kodi component at all?? What do you think? If you think it's way too much effort than what it's worth, I'm happy to just dump these PRs and let it die.

**Comment by ronie** [comment]
@basrieter can we have you final verdict please? :-)

**Comment by basrieter** [comment]
I will check it tomorrow. I am currently out.

**Comment by basrieter** [comment]
Let's start with fixing: `ERROR: ./script.module.unmanic/lib/unmanic/service.py is marked as stand-alone executable` please.

**Comment by basrieter** [comment]
So, I double checked and discussed within the team and I we are of the opinion that hosting the complete UnManic stack in Kodi not really preferred. We understand that you want to integrate UnManic within Kodi, but we would suggest you to submit a more "slim" add-on that communicates with an already existing hosted instance of UnManic. 

So we do appreciate your effort and work on the software, and encourage you to keep contributing, but we do hope you understand our viewpoint?

**Comment by Josh5** [comment]
> So, I double checked and discussed within the team and I we are of the opinion that hosting the complete UnManic stack in Kodi not really preferred. We understand that you want to integrate UnManic within Kodi, but we would suggest you to submit a more "slim" add-on that communicates with an already existing hosted instance of UnManic. 
> 
> So we do appreciate your effort and work on the software, and encourage you to keep contributing, but we do hope you understand our viewpoint? 

Oh, yea I totally understand. I've started working on an android TV application to run the Unmanic service. Let's put a pin in this add-on and I'll come back to it later this year to make it a stand alone add-on of some kind. Thanks for taking a look. And thanks for your work with Kodi's other add-ons.

**Comment by basrieter** [comment]
Thanks for understanding! We will be looking out for the more light weight add-on.

**Pull request closed without merging**
