### PR TITLE
[script.module.trakt] 2.13.0

### PR DESCRIPTION
**Pull request by Razzeee**
### Description

Updated due to problems. Be advised, this is the same version as in jarvis (https://github.com/xbmc/repo-scripts/tree/jarvis/script.module.trakt) only difference is the lower kodi dependency. The version number is the same, if that's a problem please let me know.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [sciprt.foo.bar] v1.0.0

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
That will indeed cause issue iirc. Our repo script will pull some version but not sure which

**Comment by Razzeee** [comment]
Thought that might be the case. Naming it `2.12.0~v1` should work?

**Comment by Razzeee** [comment]
Changed to `2.12.0~v1`

**Comment by MartijnKaijser** [comment]
i have no idea if that will even work or how kodi will compare the versions

**Comment by Razzeee** [comment]
Okay, the original work this is based upon has gone from 2.12.0 to 2.13.0 recently. I'll just update to the new version.

**Pull request merged**
