### PR TITLE
[script.tvthemes] v1.0.0

### PR DESCRIPTION
**Pull request by latts9923**
### Description
Addon name:  TvThemes
Addon summary:  TvThemes will allow you to organize and play Movie/TV themes while browsing your Kodi library, when used in conjunction with a compatible skin.  This will play only LOCAL media (audio named theme.mp3/.wma/.flac/.m4a/.wav or video named theme.mp4/.mkv/.avi/.mov).
Addon location:  https://github.com/latts9923/script.tvthemes
### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [sciprt.foo.bar] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by robwebset** [comment]
Seriously?

This is a complete rip-off of TvTunes. This guy has just copied the TvTunes source (complete with my comments in the code) and re-released it under his name. (This is my rewritten version - not the old buggy one from Eden several years ago)

Considering how I was treated on the forum over my addons and then the way that uRepo was automatically banned just with the mention of any code I'd touched - is this seriously going into the official repository?

It's pretty low!

Is this how the Kodi team and community is working now - ban people and then plagiarize their work?

**Comment by Razzeee** [comment]
Someone makes a pull request (which isn't even mergable)  and you instantly panic and start throwing stuff at team kodi?

**Comment by latts9923** [comment]
@robwebset

Sir, I meant no offense.  A lot of us love the TVTunes script, and I stated on the forum that I had used your code to make a new Addon that would play only local files since it had been disabled on the new Krypton release.  Would you be willing to release a new version that did the same?

**Comment by robwebset** [comment]
@latts9923 - I can not release anything into the official repo or comment on the Kodi forums - I have been banned - people will need to get any of my addons they wish to use from their new home.

**Pull request closed without merging**
