### PR TITLE
[script.service.ltvpl] 1.0.0

### PR DESCRIPTION
**Pull request by jmooremcc**
### Description

The Live TV Playlist add-on allows PVR users to create a list of their favorite live TV
shows. It will automatically change the channel to your favorite show a few seconds before your program is scheduled to start. Among its many features is the ability of the playlist to easily accommodate recurring TV shows, such as those that air on a daily or weekly basis as well as on weekdays and weekends

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by Rechi** [comment]
Trying to install this add-on fails with the following error.
```
DEBUG: CAddonInstallJob[script.service.ltvpl]: requires xbmc.gui version 5.12.0 which is not available
ERROR: CAddonInstallJob[script.service.ltvpl]: The dependency on xbmc.gui version 5.12.0 could not be satisfied.
```

**Comment by Rechi** [comment]
@jmooremcc this add-on isn't Python 3 compatible, but all add-ons in Leia branch and higher have to be Python 3 compatible (see https://kodi.tv/article/attention-addon-developers-migration-python-3).

**Comment by jmooremcc** [comment]
My add-on requires the use of the enum package which is not included normally under Python 2.7.
I've added a library for enum under the lib2 directory  which is only used when running under Python 2.7. Under Python 3.0, the enum package is available by default. My add-on excludes this package when it runs under Python 3.x.

**Comment by Lunatixz** [comment]
Please remove enum34 from your lib and pack as an individual module. If you modified the module to work within Kodi please use your name as the author (addons.xml) If this is a clone of the master please use the original author. Keep version numbers the same as the master; You can follow the below as a guideline. https://github.com/Lunatixz/KODI_Addons/tree/master/script.module.schedule

**Comment by jmooremcc** [comment]
> Please remove enum34 from your lib and pack as an individual module. If you modified the module to work within Kodi please use your name as the author (addons.xml) If this is a clone of the master please use the original author. Keep version numbers the same as the master; You can follow the below as a guideline. https://github.com/Lunatixz/KODI_Addons/tree/master/script.module.schedule

I created the independent enum34 module and submitted it in this pr along with my updated add-on. I got the following error: 

> ERROR: Required dependency script.module.enum34 is not available in current repository

What should I do next to resolve this?

**Comment by jmooremcc** [comment]
script. module. enum34 is used by script.service.ltvpl. The two add-ons are packaged together for submission to the repository.

**Comment by jmooremcc** [comment]
> @jmooremcc this add-on isn't Python 3 compatible, but all add-ons in Leia branch and higher have to be Python 3 compatible (see https://kodi.tv/article/attention-addon-developers-migration-python-3).

I've resolved the Python 3 issues. I've also separated the enum module as a separate module per Lunatixz suggestion. However, the autocheck is rejecting this change because the enum module is not already in the repository. The enum module and my add-on are essentially one package for the purpose of submitting to the repository. 

Any suggestions for resolving this issue will be greatly appreciated.

**Comment by Lunatixz** [comment]
@jmooremcc I don't see an open PR for the enum module... You need to submit the PR first. Thanks

**Comment by jmooremcc** [comment]
> @jmooremcc I don't see an open PR for the enum module... You need to submit the PR first. Thanks

The reason I was having problems previously with the code review was because I was hesitant to edit/modify the enum module. I separated it per your previous advice and discovered and fixed all the issues in the enum module the code review recommended. That's when I ran into the issue about the enum module not in the Kodi repository.
I know you're busy with your own projects so since I hadn't heard from you, I re-integrated the modified enum module back into my add-on and it passed the code review. I've tested it under both Python 2.7 and 3.x and have not encountered any problems. BTW, my add-on automatically excludes the module when it is running in a Python 3.x environment. I intend to remove it completely for Kodi version 19 since it won't be needed.
Thanks

**Comment by enen92** [comment]
@jmooremcc please submit the enum module as a script.module otherwise I doubt anyone will accept the pull request

**Comment by jmooremcc** [comment]
> @jmooremcc please submit the enum module as a script.module oth

I’m very new to this process of pull requests and I’m totally lost on how to create another pull request when I have an existing one open.
I tried creating a new pull request for the enum module but I get this screen and don’t know what to do to get past it.

[screenshot](https://github.com/jmooremcc/Live_TV_Playlist/blob/master/screenshot1.png)

Any advice you could offer will be greatly appreciated.

Thanks.

**Comment by enen92** [comment]
@jmooremcc :

```
git branch my_new_branch
git checkout my_new_branch
git remote add upstream git@github.com:xbmc/repo-scripts.git
git fetch upstream
git reset --hard upstream/leia
```
Then do your changes. In the end push them to your new branch:
```
git push -u origin my_new_branch
```
And create your PR via the github web ui.

To go back to this branch (leia from your fork) and continue working on this submission execute:
`git checkout leia`

**Comment by jmooremcc** [comment]
> @jmooremcc please submit the enum module as a script.module otherwise I doubt anyone will accept the pull request

@enen92 
I've created the pull request (#1103) for the enum module.
I'll wait until it's accepted before updating my add-on's PR (#1079 ).

What was confusing me was how to create a separate pull request utilizing the forked kodi repo.
Based on the information you provided me, I now know how to do this. 
Thank you again for your help.

**Comment by jmooremcc** [comment]
> @jmooremcc please submit the enum module as a script.module otherwise I doubt anyone will accept the pull request

I've followed your latest directions and created a new PR (#1104)

**Pull request closed without merging**
