### PR TITLE
[script.module.arlo2] 1.2.33

### PR DESCRIPTION
**Pull request by JavaWiz1**
### Description
Patched version of script.module.arlo due to issue with sseclient package (patched version - script.module.ssearlo).
Once these two script modules are merged, I will submit the fixed version of plugin.video.arloview.
### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by enen92** [comment]
@JavaWiz1 why the need to change the addon id? Is script.module.arlo not used anymore? If so please mark it as broken.

**Comment by JavaWiz1** [comment]
@enen92, this has changed because I didn't want it to get automatically updated to v0.0.24 (I did not update it, someone/something else did).  When sseclient was updated to v0.0.24, it broke the plugin, so I want to be in control of when this code gets updated.

**Comment by enen92** [comment]
I mean why name it script.module.arlo2 instead of script.module.arlo

**Comment by JavaWiz1** [comment]
Ah, you're right.  For some reason, I thought this package had to be renamed also.  I will close this PR and create a new one for script.module.arlo.

**Pull request closed without merging**
