### PR TITLE
[script.module.simpleplugin3@krypton] 3.0.5

### PR DESCRIPTION
**Pull request by vlmaksime**
### Add-on details:

- **General**
  - Add-on name: SimplePlugin 3
  - Add-on ID: script.module.simpleplugin3
  - Version number: 3.0.5
  - Kodi/repository version: krypton

- **Code location**
  - URL: https://github.com/romanvm/script.module.simpleplugin
  
SimplePlugin micro-framework that simplifies Kodi content plugin programming.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by vlmaksime** [comment]
This add-on used at weather.gismeteo

**Comment by Lunatixz** [comment]
@vlmaksime How does simpleplugin3 differ from its upstream simpleplugin?

Could those changes have been implemented locally in your weather.gismeteo script?

**Comment by vlmaksime** [comment]
> How does simpleplugin3 differ from its upstream simpleplugin?

SimplePlugin v.3.x has simplified API is not compatible with previous versions. That is why it uses a different addon ID: script.module.simpleplugin3. [(source)](https://romanvm.github.io/script.module.simpleplugin/)


> Could those changes have been implemented locally in your weather.gismeteo script?

This module broke the compatibility of weather.gismetio with Kodi 19 several times. The module is initially a standalone add-on, so I decided to move it out for ease of updating in case of future compatibility problems.

**Review by ronie — APPROVED** [review]
looks good to me, thx!

**Pull request merged**
