### PR TITLE
Omit the additional info from PRs

### PR DESCRIPTION
**Pull request by Razzeee**
This change will still show the infos when a submitter is filling in a PR, but it will be hidden from the actual PR.

### CODE REVIEW

**Comment by Razzeee** [comment]
@MartijnKaijser please review.

I will do a typo correction run after this

**Comment by hudokkow** [comment]
looks good

**Comment by MartijnKaijser** [comment]
i actually left it there by intention

**Comment by Razzeee** [comment]
Okay, why would that be good?

**Comment by MartijnKaijser** [comment]
Cause most do t read what's in that description. Once they complete the PR its in their face and also for other to see

**Pull request closed without merging**
