### PR TITLE
[service.subtitles.legendasdivx] 0.2.9

### PR DESCRIPTION
**Pull request by highlandr**
Better search results.

### CODE REVIEW

**Comment by basrieter** [comment]
Please make Travis happy and fix your issues in `addon.xml`, fix the language files and then update this PR.

**Comment by highlandr** [comment]
I didn't fix the lang because of gotham? isn't it only compatible after Isengard?

**Comment by highlandr** [comment]
> Please make Travis happy and fix your issues in `addon.xml`, fix the language files and then update this PR.

I didn't fix the lang because of gotham? isn't it only compatible after Isengard?
I have the files ready.

**Comment by basrieter** [comment]
Gotham should support PO files

**Pull request closed without merging**
