### PR TITLE
[context.tags] 0.0.5

### PR DESCRIPTION
**Pull request by zosky**
### Description

krypton requires &lt;assets&gt; in addon.xml for icon & fanArt. [wiki:addon.xml:assets](http://kodi.wiki/view/addon.xml#.3Cassets.3E)

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [ ] Each add-on submission should be a single commit with using the following style: [script.foo.bar] v1.0.0

### Can't Squash :-1: 
sorry, i can't figure this out. i'm doing what it says for updating at the bottom of [submitting PRs wiki](http://kodi.wiki/view/HOW-TO:Create_add-on_PRs_using_Git_Subtree_Merging) and i tried following a few stackOverflow threads but no dice.

### CODE REVIEW

**Comment by zosky** [comment]
git complained about a conflict and i _fixed it_. 
( i dont think im doing this right ? )

**Comment by enen92** [comment]
@zosky please change your PR title to the standard format "[script.x] version". If your intention was only to update the addon.xml of your addon, changes do look correct.

**Comment by zosky** [comment]
sorted

**Comment by enen92** [comment]
thanks

**Comment by enen92** [comment]
@zosky can you please submit an icon and a fanart on the next update? It doesn't look good on the website: https://kodi.tv/addons/context-menus

**Comment by zosky** [comment]
i noticed that too, thats what i was trying to fix with this PR. i logged into the dev IRC channel and rechi told me to add assets in addon.xml. does that sort out the site too or do i need to do something else for that ?

**Comment by enen92** [comment]
See here: https://github.com/zosky/kodi.context.tags/issues/1

You basically need to put an icon.png and fanart.jpg in the resources folder of your addon. Then, in the addon xml just define the assets tag pointing to both images
```
<assets>
    <icon>resources/icon.png</icon>
    <fanart>resources/fanart.jpg</fanart>
</assets>
```

**Pull request merged**
