### PR TITLE
[screensaver.digitalclock] 3.6.0

### PR DESCRIPTION
**Pull request by vdb86**
My first attempt at doing this instead of mailing list.
Keeping my fingers crossed!

### CODE REVIEW

**Comment by learningit** [comment]
Why are there multiple commits? The PR should be after all commits locally.

**Comment by vdb86** [comment]
I must have done something wrong.
Sorry about that, let me see how to fix it.

**Comment by learningit** [comment]
Easiest way I've found is to close this request, go back and create a new unique branch from the base xbmc repo, apply all changes then create a PR from the unique new branch

**Comment by vdb86** [comment]
Will do, thanks!

**Pull request closed without merging**
