### PR TITLE
[script.skinshortcuts] 1.0.19

### PR DESCRIPTION
**Pull request by finkleandeinhorn**
This simply brings the repo version of Skin Shortcuts even with @marcelveldt's beta repo version, which has been significantly ahead for a number of years now.

### CODE REVIEW

**Comment by finkleandeinhorn** [comment]
Victory! Let me know if I need to fix anything else :grin:

**Comment by finkleandeinhorn** [comment]
Is this a mergeable request? Or do I need to make further changes?

**Comment by sualfred** [comment]
As far as I remember the version of Marcels repo had some issues and is and was never the upstream of the skinshortcuts script. 
The version for Leia and below is https://github.com/BigNoid/script.skinshortcuts/commits/master

**Comment by enen92** [comment]
@basrieter we don't request squashing commits anymore, we do it in github if needed. We must try to avoid the pain as much as possible :)

@sualfred would be nice to get your review here before wasting time checking more than 100 files.

**Comment by finkleandeinhorn** [comment]
I'm haven't been aware of any instability in @marcelveldt's version, which was 1.0.18 until very recently.

The only change in 1.0.19 was a fix to properly URL encode paths retrieved using the "Just Select" method.

Almost all of the changes in the PR are simply syntax changes requested by Travis, with (if I recall correctly) only one line changed between the last two versions from the repo.

**Comment by sualfred** [comment]
@finkleandeinhorn 
I only have a problem with it because it's a fork of the original work. And the fork itself is abandoned since more than just months.  And there was a issue, which I cannot remember. The last time I used inofficial versions of his repo was over a year ago.

I know it's a special situation because the fork and the upstream have no active maintainer at the moment.

Just compare the two repositories:
https://github.com/marcelveldt/script.skinshortcuts/commits/master
vs
https://github.com/BigNoid/script.skinshortcuts/commits/master

The original upstream of BigNoid is a view commits ahead compared to the one of Marcel as far as I can see. 

I suggest you to fork BigNoid's version, apply your URL encode change and other required fixed and then submit it again.

**Comment by basrieter** [comment]
I am going to close this PR. The main reason behind it is that this a PR that does not originate from the maintained version of @mikesilvo164. We do appreciate all efforts in supporting Kodi and add-ons.

As suggested by @sualfred you can fork either @mikesilvo164 or @BigNoid 's and do a PR in their repos. Perhaps ask @mikesilvo164 which one would be best.

**Pull request closed without merging**
