### PR TITLE
[script.module.arrow] 0.12.1

### PR DESCRIPTION
**Pull request by Razzeee**
Updates arrow to the lastest version

### CODE REVIEW

**Comment by Rechi** [comment]
This version isn't compatible with Python 2.6.

**Comment by Razzeee** [comment]
Which branch is the one to target then?

**Comment by Rechi** [comment]
For a non Python 2.6 compatible version, Krypton.
There is a newer version of this module, which is Python 2.6 compatible.

**Comment by Razzeee** [comment]
Not sure what your hinting at, https://pypi.org/project/arrow/ states it's only 2.7 and above. And that's the newest tagged version.

**Comment by Rechi** [comment]
Have a look at https://github.com/crsmithdev/arrow/releases and find the last version which supports Python 2.6.

**Comment by Razzeee** [comment]
Ah, that's your point :) 
0.12.1 would be what we want

**Comment by Razzeee** [comment]
Updated PR to that version. My branch name might be a bit confusing.

**Pull request merged**
