### PR TITLE
[script.tvtunes] 6.3.1

### PR DESCRIPTION
**Pull request by robwebset**
Please can I have the following small update merged in. (Prevents needless processing)

Thanks,
Rob

### CODE REVIEW

**Comment by robwebset** [comment]
Thanks @MartijnKaijser

**Comment by SchapplM** [comment]
I noticed, that a few files in your addon have CRLF line endings checked in (instead of LF).
That leads to a conflict on linux systems (conflicted files in git repo prevent ability to merge/stash).
Could you change the endings in the following files?

	               plugin.py
	               resources/lib/idLookup.py
	               resources/lib/library.py
	               resources/lib/screensaver.py
	               resources/lib/themeFinder.py
	               resources/lib/upload.py
	               saver.py

I did not see this in your addon-repo https://github.com/robwebset/script.tvtunes though.
Thanks

**Comment by tamland** [comment]
@SchapplM there is a .gitattributes that should make it impossible to submit crlf but I think the problem is that it was already in in some branches, and it wasn't cleaned properly when added. Feel free to follow https://help.github.com/articles/dealing-with-line-endings/#refreshing-a-repository-after-changing-line-endings and submit a PR.

**Comment by robwebset** [comment]
Hi @SchapplM 

No problem, new pull request: https://github.com/xbmc/repo-scripts/pull/134

I have noticed that some of my other addons also suffer the same issue - should I convert those and do a new pull request for them as well?

Thanks
Rob

**Pull request merged**
