### PR TITLE
[script.module.guessit] 2.1.4

### PR DESCRIPTION
**Pull request by ramiro**
### Description
`script.module.guessit` is GuessIt (http://guessit.io) packaged as a Kodi add-on.

GuessIt is a Python library that allows you to define simple search patterns in bulk to perform advanced matching on any string.

Example of usage:

```python
>>> import guessit, pprint
>>> pprint.pprint(guessit.guessit('The.Matrix.1999.720p.BRRiP.HEVC.x265.AC3-MAJESTIC.mkv'))
MatchesDict([('title', 'The Matrix'),
             ('year', 1999),
             ('screen_size', '720p'),
             ('format', 'BluRay'),
             ('video_codec', 'h265'),
             ('audio_codec', 'AC3'),
             ('release_group', 'MAJESTIC'),
             ('container', 'mkv'),
             ('mimetype', 'video/x-matroska'),
             ('type', 'movie')])
```
It can help Kodi add-ons which need to extract meta-data from video file names in a canonical/efficient way and avoid reinventing the wheel badly.

It depends on:

* `script.module.dateutil` (already available in Kodi repos)
* `script.module.babelfish` (submitted in #813)
* `script.module.rebulk` (submitted in #814)

### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [script.foo.bar] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by enen92** [comment]
@ramiro is this a dependency of any submitted addon? The general rule is that we only accept modules if they are used as a dependency. I'll review them but keep it mind they will only be merged when an addon uses it.
Nice module either way :)

**Comment by ramiro** [comment]
We plan to use it in a new release of an existing add-on: [`service.subtitles.subdivx`](https://kodi.wiki/view/Add-on:Subdivx.com). we have a ticket open for this feature at (in Spanish) ramiro/service.subtitles.subdivx/issues/28 and it's the next feature I plan to look at.

subdivx.com has no API so we must resort to scrape the website. Also, subtitles submissions aren't forced to follow a strict format but simply a free form comment.

This makes hard to rank and order the different subtitles choices scraped for a given video when trying to make sure the ones that best match it appear in the top of the search result list.

Subttitle contributors usually use that free form comment field to mention the release type, group, etc. so the idea is to detect and match the presence of a few metadata item values there and devise some way to quantitatively use it to rank entries.

**Comment by enen92** [comment]
@ramiro ok thanks for the info. I'll review them (not that I expect any change wrt the original modules) so that when you submit the subtitle addon the process is quicker.

**Comment by enen92** [comment]
ping @ramiro

**Comment by ramiro** [comment]
@enen92 I plan to upload a version of `service.subtitles.subdivx` that uses guessit & co next week. Thanks for the reminder!

**Comment by enen92** [comment]
ping @ramiro I'll close all PRs by sunday night (GMT time) if nothing is done. Staying in the queue for too long.

**Pull request closed without merging**
