### PR TITLE
[script.module.inputstreamhelper] 0.3.4

### PR DESCRIPTION
**Pull request by emilsvennesson**
### Description
+ python2_3 compability (mediaminister, Rechi)
+ Option to disable inputstreamhelper in settings.xml
+ calculate disk space on the tmp folder (dawez)
+ Support for Unicode paths in Windows (WallyCZ)
+ Italian translation (pinoelefante)
+ Dutch translation (dnicolaas)
+ Greek translation (Twilight0)
+ Russian translation (vlmaksime)

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [script.foo.bar] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by dagwieers** [comment]
@emilsvennesson I think by requiring `kodi-six` in this addon, every addon that is using **inputstreamhelper** also needs to add `kodi-six` in its requirements. At least on my system it was unable to find kodi_six because its path was not automatically included for the addon (not being part of the addons requirements).

That's why I would not add `kodi_six` as a requirement and simply add the needed PY2/PY3 provisions in your own code, like we did for **plugin.video.vrt.nu**.

**Comment by emilsvennesson** [comment]
@dagwieers You don't need to add it as a dependency for your add-on. It will automatically get installed because the module depends on it.

I'm going to stick with kodi-six (for now at least) because it saves us the headache of dealing with the py2/3 unicode mess.

**Comment by dagwieers** [comment]
Sure, it gets installed, but in my case it wasn't able to import it because the addon did not have it in its requirements. So having it installed is not sufficient, every addon needs to require it in addon.xml for the kodi_six library path to be included so the addon can import it. (I know this is weird, but I got bitten by this for **script.module.pysocks**)

**Comment by dagwieers** [comment]
For **plugin.video.vrt.nu** we don't have any unicode issues by just using:
```python
from __future__ import unicode_literals
```

**Comment by dagwieers** [comment]
I am just saying that I think all addons will start failing as soon as this gets out...

**Comment by emilsvennesson** [comment]
That doesn't make any sense. It would mean that all add-ons would have to add the dependencies of all its modules. 

I've tried it with plugin.video.viaplay and it works just fine on all of my Kodi installs.

**Comment by dagwieers** [comment]
I straced Kodi and that was what I saw. Having a library installed doesn't ensure its path will be included for python. See: https://github.com/pietje666/plugin.video.vrt.nu/pull/93#issuecomment-476287321

**Pull request merged**
