### PR TITLE
[script.safekodi] 1.0.0

### PR DESCRIPTION
**Pull request by yunmingxiao**
### Description

SafeKodi will examine the addons installed on local machine, and provide addon suggestions.
SafeKodi is built on top of de-kodi, a tool that crawls addons and checks the safety of addons. The details of de-kodi will be presented in the World Wide Web Conference 2020 (https://www2020.thewebconf.org/).  

More information about the Safekodi project please refer to (safekodi.com) and (https://yunmingxiao.github.io/projectsfolder/dekodi/). The pages are still under construction.

### Checklist:

- [Y] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [Y] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [Y] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by enen92** [comment]
Hey @yunmingxiao thanks a lot for your submission to Kodi.

While I understand this was developed with good intentions I don't think we can accept such an addon into our repository. Kodi addon ecosystem is inherently unsafe since python is not sandboxed at all. We are responsible for the official repository and try to check every single addon submission either for security vulnerabilities or for other issues the addon might pose to the user. If some addon is found vulnerable in our repo, we encourage everyone to reach to us so that we can fix the issue as soon as possible. 
We can't be responsible for every single third party addon, stored in "god knows where" without passing any review process. Kodi by design does not accept external addon installations and the user himself has to toggle that security setting to be able to install addons or external repos by zip file. Kodi warns the user, if he wants to proceed with a third party addon installation...it's his problem afteral. We do not control nor restrict how users use Kodi (nor will we ever do).

A few more issues with your addon:

- You're using a self signed certificate for a service that is supposed to warn users about potential security holes in their kodi installation.
- You're sending the installed addon list to a third party location, thus completely violating the user privacy
- Safekodi branding is violating our trademark policy. See: https://kodi.wiki/view/Official:Trademark_Policy

While we thank you for the submission, a proper solution to this problem would be to improve the kodi addon ecosystem to sandbox python somehow.

For the reasons mentioned above, I'll have to reject the addon submission. 
Good look for your paper presentation though.

Thanks

**Comment by svarvel** [comment]
Hey @enen92 , I am also involved in this work. Few clarifications about your comments: 

1) can you please clarify what you mean by <<You're using a self signed certificate for a service that is supposed to warn users about potential security holes in their kodi installation.>>? Our backend runs at https://safekodi.com/ which uses a certificate provided by Let's Encrypt, not a self-signed certificate. 

2) about sending the addons list to a third party location -- a) would it be ok to show a warning to the users? b) would you consider acceptable a privacy preserving solution, aka we go through a CDN (not getting IP), and only collect the list without any user info? We can also provide an IRB, if this helps. We need to get the addon list remotely since many addons are unknown and this triggers our crawler to fetch the addon, test it, evaluate it, and then report to the Kodi users. 

3) about the branding violation -- we were not aware, we can change the name.

**Comment by Lunatixz** [comment]
@yunmingxiao @svarvel 

There is a flaw with the "safekodi" thesis; The notion that Kodi's addons are decentralized, as you can see by our repository Kodi has a centralized source for safe "third-party" addons. Any addons found outside this repository are inherently unsafe because the code has not been analyzed by Kodi Team members. In short, declaring a "third-party" addon" as "safe" is our responsibility. Kodi welcomes all "third-party" developers to submit their projects for review.

**Comment by svarvel** [comment]
@Lunatixz I understand your point and appreciate your response. This seems to be just a terminology problem and we are happy to reword and come up with another proposal, if you think this can help in getting approved.

**Comment by enen92** [comment]
Have a look into https://github.com/xbmc/addon-check if you somehow want to contribute to our tooling

**Comment by yunmingxiao** [comment]
> Have a look into https://github.com/xbmc/addon-check if you somehow want to contribute to our tooling

@enen92 @Lunatixz  

Thank you for sharing the add-on checker with us. But what we are doing is kind of different from static code checking. We cannot share the paper with you before the conference, but we can briefly tell what we are doing. We first crawl the add-ons that are not limited to the official repository. We install and run the add-on one by one in a sandbox and we audit if there is any network traffic between the add-on and the current known URLs and IPs that contain tacking, ads, threats, and malware. 

And I'd also like to declare that we are not intending to warn the users on behalf of Kodi official. We'd like to add notes like ‘the suggestions are made per our study’ in our add-on and websites so long as you would consider appropriate to prevent any misunderstanding. 

Regarding user privacy issues, we can provide an IRB if it helps. We will anonymize the data. We can also prompt a window asking users' permission before sending the installed addon list. Or do you have any suggestions that you think would be appropriate?

**Comment by enen92** [comment]
We understand what your tool does and we appreciate your interest in Kodi, but we have **zero** interest in what add-ons that are not in the official repository do.

Kodi add-ons are inherently unsafe, python has system level access and is not sandboxed. Any other type of checking that doesn't mean fixing this issue only provide a false sense of security and only serves academic purposes.

**Pull request closed without merging**
