### PR TITLE
[script.colorbox] 1.0.10

### PR DESCRIPTION
**Pull request by BADMS**
new version

### CODE REVIEW

**Comment by BADMS** [comment]
ignore 1.0.9 on commits 1.0.10 is as addon.xml

**Comment by phil65** [comment]
Please PR just one commit with a correct version number.

**Comment by BADMS** [comment]
Sorry, a bit of mess due to no real feedback. Have now created pull via github repo if this is OK?
On 17 Apr 2016 12:56 p.m., Philipp Temminghoff <notifications@github.com> wrote:Please PR just one commit with a correct version number.

**Comment by BADMS** [comment]
Actually I see now where I'm at, will correct and resubmit pull on git! Apologies. 
On 17 Apr 2016 12:56 p.m., Philipp Temminghoff <notifications@github.com> wrote:Please PR just one commit with a correct version number.

**Pull request closed without merging**
