### PR TITLE
[script.module.pyqrcode] 0.0.1

### PR DESCRIPTION
**Pull request by Lunatixz**
### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [sciprt.foo.bar] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by Lunatixz** [comment]
Module is required for upcoming kodi loguploader update: https://github.com/XBMC-Addons/script.kodi.loguploader/pull/1

**Comment by learningit** [comment]
Ok. I reviewed the code and it looked ok in the helix PR, It's basically a standard service module from another author so there's not much to comment on in terms of style.

I won't merge until the loguploader is submitted to the kodi.org repo (I don't think it has yet anyway, if so let me know which branch). We, as a rule, don't allow modules that aren't used by at least one add-on in the official repo.

**Comment by Lunatixz** [comment]
The module rule sounds reasonable, in this case ping @ronie he has final word. We just need to remember to commit this first before the loguploader commit : )

**Comment by learningit** [comment]
Thanks. NP, we'll know soon enough if we forget believe me.

**Comment by ronie** [comment]
> I won't merge until the loguploader is submitted to the kodi.org repo (I don't think it has yet anyway, if so let me know which branch).

will push it to jarvis in a minute..

**Pull request merged**
