### PR TITLE
[service.watchedlist] 1.2.7

### PR DESCRIPTION
**Pull request by SchapplM**
Please merge these minor changes in my addon

### CODE REVIEW

**Comment by Razzeee** [comment]
Please at least resolve the two problems jenkins buddy mentions

**Comment by SchapplM** [comment]
now it should be fine

**Comment by Rechi** [comment]
> Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Please squash the commits.

**Comment by SchapplM** [comment]
done: squashed commit with force push

**Pull request merged**
