### PR TITLE
[script.module.ijson] 2.3

### PR DESCRIPTION
**Pull request by tuxpoldo**
### Description
Ijson is an iterative JSON parser with a standard Python iterator interface. This library allows to parse giant json files without the need to load them in memory.
### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [script.foo.bar] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by tuxpoldo** [comment]
This library will be used by the new addon [plugin.video.mediathekview] that I'm about to publish in the next few days. I'm creating this pull request now, since I want to make sure, that the dependencies will be resolved when the new addon will be published.

**Comment by romanvm** [comment]
LGTM

**Comment by tuxpoldo** [comment]
Seems like Codacy does not like lambdas: it remarks "Lambda may not be necessary" two times. Unfortunately I cannot change the code of the original library but it works perfectly and in my opinion this should absolutely not be a problem...

**Comment by romanvm** [comment]
@tuxpoldo Don't bother. I too find Codacy to be too overzealous.

**Comment by tuxpoldo** [comment]
Any Idea, when the PR will be merged?

BTW: The source of the plugin that will use this library is now on GitHub: https://github.com/YeaSoft/plugin.video.mediathekview

**Comment by tuxpoldo** [comment]
TNX!

**Pull request merged**
