### PR TITLE
[service.fhemcinema] 0.3.1

### PR DESCRIPTION
**Pull request by Memphiz**
### Description
While playing with the CinemaVision addon i found a problem as follows.

I have configured the Home Cinema Automation addon to switch on my lights when playback stops. The CinemaVision addon plays multiple trailers and video bumpers before starting the actual movie. This leads to sort of light on, off, on, off situation.

This pull request adds a setting which allows to delay the execution of the stop command. This prevents the flicker and only executes that command if the movie was stopped for the given time.

Defaults to zero so this is backward compatible behavior.
### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [script.foo.bar] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

This needs a signoff by upstream @tuxpoldo which got a pull request with the changes as well.

### CODE REVIEW

**Comment by Tadly** [comment]
LGTM.

Just not sure how we handle PRs that update someone elses add-on?
@Memphiz have you contacted the original author?

**Comment by Memphiz** [comment]
Yes I did a PR with this change to upstream repo and pinged him in this very PR

**Comment by Tadly** [comment]
Whups.. Completely missed your ping at the very bottom there. My bad :)
Right, lets wait for his response than.

**Comment by Memphiz** [comment]
@tuxpoldo are you still active on GitHub at all? ;)

**Comment by tuxpoldo** [comment]
Hi! Sorry for the delay. I merged the pull request in the original project. I'm fine with the change - please merge it.

@Memphiz thank you!

**Comment by tuxpoldo** [comment]
@Tadly - I'm fine with the pull request. Please go on.

**Pull request merged**
