### PR TITLE
[script.module.requests-cache] 0.0.1

### PR DESCRIPTION
**Pull request by gedisony**
### Description
hi enen92: 
I packaged requests-cache into a kodi module. 

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by enen92** [comment]
@gedisony thanks for adjusting and turning this section into a separate module. Note that for this to be merged there should be at least an addon that uses it. So please send a pull request with an update to the reddit addon with the requests-cache code removed and using this one as a dependency. Thank you much
No hurry at all, take your time

**Comment by gedisony** [comment]
Okay, I'll prep an update on the reddit addon. My local tests was working fine but I wanted to put the requests-cache module in the repo first to test the actual downloading dependency part.

**Comment by Razzeee** [comment]
We're pretty sure that part works, as so many addons are already using dependencies :)

**Comment by gedisony** [comment]
Should I close this PR and do a different one with both addons?

**Comment by enen92** [comment]
@gedisony the module should be one PR (merged first) then the addon

**Comment by gedisony** [comment]
please don't get mad. i don't know github and this is trial and error.

**Pull request closed without merging**
