### PR TITLE
[script.video.funimationnow] 0.1.0

### PR DESCRIPTION
**Pull request by Protocol-X**
### Description
Updated code to use new API as old one is being deprecated.
Created custom UI so look and feel will be universal across all devices.

### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [sciprt.foo.bar] v1.0.0

### Issues:
Auto Check is marking a section of code as unused when it is actually being used.
- line 688 of maingui.py
-- [i.start() for i in threads];

### Note:
Once accepted please remove or mark broken the old version of the addon in the repo-plugins
- Jarvis: [plugin.video.funimationnow] 0.0.3

### Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by Protocol-X** [comment]
@ronie , Can you look at this?  This keeps failing even know it is legitimately used.  It doe snot need an assignment. 

If this can be ignored then no need to look into it.  Not sure if this check fail is an automatic denial.

**Comment by ronie** [comment]
yup, you an ignore it if it's valid code.

**Comment by Protocol-X** [comment]
@ronie Thank you.  I was not sure if this auto check automatically prevents your team from looking into the PR.    
Much appreciated

**Comment by richdroid** [comment]
First off thanks so much Protocol-X for all the work you do on the add-on!  I was having the playback problem that you patched with the new zip, so I installed the new add-on but, it doesn't work and it just sends me to a purple screen with a small search button in the corner (I attached a picture) and it
img_20170117_194049989
 freezes. Is this something you can replicate on your side? Or is my device (an Apple TV) not powerful enough to handle it? PS sorry this is the only way I could find to contact you.

**Comment by Protocol-X** [comment]
@richdroid I can not duplicate this, I have tested on android, windows, openelec, Kodi 16
I was under the impression Apple uses 15, do you know what version you are using?  The only Time i was able to duplicate this in the past is when I had attempted to use a Texture File because it was not able to locate the resources?  Please contact me here and we can look into it, but no other beta testers have had this issue.

https://github.com/Protocol-X/script.video.funimationnow/issues/new

**Comment by richdroid** [comment]
@Protocol-X Ok I have posted it on the issues board like you said.

**Comment by Protocol-X** [comment]
FYI I confirmed richdroid is using Kodi 15.2 so this is a null issue for this PR.  The old API also shut down today as well so the old plugin will begin getting failure reports i assume.

**Comment by MartijnKaijser** [comment]
Please create a PR to mark the plugin broken and mention they should install this one

**Comment by Protocol-X** [comment]
@MartijnKaijser do I need to do that before this one can be approved, or are you just letting me know I need to do it as well?

**Comment by Protocol-X** [comment]
@MartijnKaijser sorry I misread. I will get a pr open with the plugin team and reference this pr to be installed.    Thank you

**Comment by MartijnKaijser** [comment]
@ronie @phil65 all good for merge?

**Comment by MartijnKaijser** [comment]
@Protocol-X the location of the icon.png and screenshots is wrong compared to what you specify in addon.xml.
Please fix and send an update with version bump

**Pull request merged**
