### PR TITLE
[script.module.requests@Matrix] 2.25.1+matrix.1

### PR DESCRIPTION
**Pull request by L2501**
### Description
requests-2.25.1 
Changelog https://github.com/psf/requests/blob/c2b307dbefe21177af03f9feb37181a89a799fcc/HISTORY.md
Hopefully no massive fails for rPi like last time this was updated 2 years ago
### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Review by basrieter — COMMENTED** [review]
I check the `lib` folder and it is identical to the requests-2.25.1  from PyPi. So that looks good. Did we do some specific patching for Kodi @enen92? And do we also want this version for Python 2?

**Comment by enen92** [comment]
Nop, as long as it matches against upstream it's good to go

**Comment by basrieter** [comment]
> Nop, as long as it matches against upstream it's good to go

And what about the Python 2 version @enen92?

**Comment by enen92** [comment]
It's the same, as long as it's plain upstream, that's fine. Hopefully won't cause regressions

**Pull request merged**
