### PR TITLE
[script.service.singealarmclock] 1.01

### PR DESCRIPTION
**Pull request by druscoe**
### Description
Schedule custom alarms and wake up to your favourite media.
### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by enen92** [comment]
@druscoe this is a new addon submission. We only accept updates to existing addons in older repos (gotham in this case). New addons can only be submitted to Leia and above.

**Comment by druscoe** [comment]
This has been tested on past versions of Kodi from Gotham to Leia.

Resubmitted into Leia branch

**Comment by enen92** [comment]
Superseeded by https://github.com/xbmc/repo-scripts/pull/1314

**Comment by BubbeleM** [comment]
Du dummer kleiner Wicht!!

Mit freundlichen Grüßen




Am 25.02.2020 um 16:28 schrieb enen92 <notifications@github.com>:

﻿

Closed #1284<https://github.com/xbmc/repo-scripts/pull/1284>.

**Pull request closed without merging**
