### PR TITLE
[script.skinshortcuts] v.1.0.8

### PR DESCRIPTION
**Pull request by marcelveldt**
Latest version of the skinshortcuts script.
Thanks in advance for updating

### CODE REVIEW

**Comment by Ignoble61** [comment]
With (what appear to an outsider to be) uncontroversial PR's to be waiting for up-to 2 weeks at this stage without feedback (and with someone who isn't keen to necessarily push PR's, especially ones such as this which I have no doubt will have comments from the repo-guardians that we need to fix) is there anything I can do to help speed up reviews of open PR requests?

Obviously I have this PR in mind when I ask, but also one such as #135 - the CRLF's which that fix contributed to me being unable to make this PR myself ;)

Thanks for your time.

**Comment by Ignoble61** [comment]
Many thanks, Phil. Though that really wasn't intended as a push to get this particular PR merged and, as said, if there's anything I can do (as an untrained individual) to help smooth the PR method whilst it gets shaked-down, please do let me know.

**Comment by phil65** [comment]
Sorry, main issue is that we´re just short on manpower in this department atm.

**Comment by Ignoble61** [comment]
There's absolutely no need to be sorry :)

Given recent events, I'd much rather wait for a good review than have the team feel under pressure (and the offer of what little assistance I can give the team is always open). I'm quite certain the fact that you've acknowledged the shortage of manpower here will help alleviate any frustration people may feel about the process :)

**Pull request merged**
