### PR TITLE
[weather.ozweather] 0.9.2

### PR DESCRIPTION
**Pull request by bossanova808**
### Description

Ok, so my 'fix' wasn't a fix.  Apparently, in sub  profiles libs can be disabled at random.  So this import was not necessary.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
I'll ping the dev who handles addon management and ask if he will check profiles. This will only be fixed for v18 though

**Comment by bossanova808** [comment]
I've checked this works with profiles - the only issue was that urllib3 was disabled in the sub-profile (the why of that is a mystery) - but I can note it in the addon wiki anyway.  Sorry I wasted your time here & many thanks for merging.

**Comment by MartijnKaijser** [comment]
np.
It might be something missing that if you install it from a non master profile it's not enabled if this addon wants it.
Also if an addon depends on a module it should at least ask/check if that's enabled and take appropriate action. I consider this a bug.

**Comment by bossanova808** [comment]
I agree - I found several disabled libs in the sub-profiles, on three different machines (all LE Krypton boxes).  None had had anything disabled manually, so it's weird and pretty confusing behaviour for a  user...

**Pull request merged**
