### PR TITLE
[screensaver.videosaver] 1.0.0

### PR DESCRIPTION
**Pull request by Lunatixz**
### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by robwebset** [comment]
Hi Lunatixz,

Just a thought, you may want to have a slightly different name other than "screensaver.video" otherwise it will clash with the following:

http://www.urepo.org/addon.php?t=15546

Thanks
Rob

**Comment by Lunatixz** [comment]
My bad, didn't realize that was the same id.

**Comment by robwebset** [comment]
No worries. Just didn't want you getting your addon overwritten by my one for anyone with the uRepo Repo installed (Which would be anyone with the TvTunes/PinSentry etc addons installed).

Thanks
Rob

**Comment by Lunatixz** [comment]
@enen92 when you get a chance pls check this out for commit, thx

**Comment by enen92** [comment]
@robwebset please refrain from mentioning banned repos or addons on the kodi official channels, github included. Your posts have been edited.
Thanks for submitting @Lunatixz

**Pull request merged**
