### PR TITLE
[script.skin.info.service] 1.1.3

### PR DESCRIPTION
**Pull request by mikesilvo164**
### Description
Encoding fix

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by mikesilvo164** [comment]
Hmm... I don't understand the conflict 😕

**Comment by pkscout** [comment]
The version that is currently in the Matrix repo is 1.1.2, so the addon.xml diff can't apply because your diff is from 1.1.1. I am not the world's best at git, but I think that means the repo-scripts clone you have isn't up-to-date. If you correct that and then submit a new PR (I'm pretty sure it needs to be a new PR), that issue should go away.

**Comment by pkscout** [comment]
Here's a suggestion from the Kodi team Slack channel that should allow you to fix this without having to submit a new PR.

> He can likely fetch, rebase, resolve conflicts(if any) and force push again.

**Comment by mikesilvo164** [comment]
I just redid the whole thing. Was the wrong branch I was using anyway lol

**Comment by mikesilvo164** [comment]
Thanks @pkscout ☺️

**Pull request closed without merging**
