### PR TITLE
[script.domoticz.scenes] 0.0.11

### PR DESCRIPTION
**Pull request by Paul-VW**
### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by basrieter** [comment]
I am confused about all the commits in this PR. There seem to be multiple add-ons in this PR: `script.domoticz.scenes` and `plugin.video.funcarrun`. Please don't do this and submit two independent PR's.

**Comment by Paul-VW** [comment]
Don't worry, I'm confused about it myself too... ;-) I've never used GitHub before, so still figuring out how this works

**Comment by basrieter** [comment]
Any update on this PR?

**Comment by basrieter** [comment]
Last *ping*

**Comment by basrieter** [comment]
Closing this for now. Please re-submit two new PR's for each of the add-on in this PR.

**Pull request closed without merging**
