### PR TITLE
[script.plex] 0.0.95 - New

### PR DESCRIPTION
**Pull request by ruuk**
### Description

This is the official Plex addon. Provides a Plex client (much like the various Plex clients currently out there) for Kodi.

We'd like to time the merge if at all possible. So if it's not a problem, I'd like to get the OK from the review but do the actual merge myself.

Thanks!

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [sciprt.foo.bar] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
\0/

**Comment by keithah** [comment]
ping @phil65 and @learningit. thx guys!

**Comment by phil65** [comment]
Sorry, but reviewing this is massive, the add-on really adds an unbelievable amount of abstraction considering what needs to be done. (imo way too much, but thats probably a matter of coding style and background.. )
I continued reviewing on gitlab. Some general remarks:
- The script workarounds our font limitations for add-ons by creating images of localized text via PIL. That really is ugly and I am not sure if we should allow that.
- There is so much all-purpose code in there, it would make lot more sense to move a hell lot of stuff to some library so it doesnt need to get coded (and reviewed) again for your next add-on.
- it would be much appreciated if we could spend efforts into adding proper hooks to our core instead of workarounding every single core limitation via python. The whole GUI part of this script is really spaghetti, sorry to say that. :) (Kodi doesnt have the proper hooks to "override" the complete OSD part for example, and any try to workaround that will end up quite ugly)

I wouldnt consider this show-stoppers, but it would really be appreciated if there would be efforts to solve problems properly first before adding huge amounts of workarounds.

**Comment by ruuk** [comment]
> I wouldnt consider this show-stoppers, but it would really be appreciated if there would be efforts to solve problems properly first before adding huge amounts of workarounds.

Fair enough, but not an option for working with the existing release :)

**Comment by learningit** [comment]
I would agree with Phil's comments regarding PIL. I've tried to sit down
and review this add-on a few times and just find it's so over engineered, I
give up after wandering through the code.

**Comment by phil65** [comment]
> Fair enough, but not an option for working with the existing release :)

Thats why I said that I wouldnt consider it show-stoppers ;) All I am saying is that it would be much appreciated if we would try to improve things by improving core or at least start some discussion / make devs aware when hitting the boundaries of what our APIs allow.

**Comment by keithah** [comment]
I spoke with Martijn and while ruuk and I understand there's a ton of workarounds presented here, ruuk and I will work on putting together a list of core changes we propose to handle these and once merged will incorporate them into the addon to make the addon system better for everyone. 
Thanks for your time and the constructive criticism you guys, I really appreciate it!

**Comment by phil65** [comment]
Sounds good. I will probably need one last review session to cover all code, I think I will get that done during this week.

**Comment by keithah** [comment]
Sounds good, thanks @phil65!

**Comment by ruuk** [comment]
FYI - removed the PIL stuff

**Pull request merged**
