### PR TITLE
[script.module.pyqrcode] 0.0.1

### PR DESCRIPTION
**Pull request by Lunatixz**
### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [sciprt.foo.bar] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by Lunatixz** [comment]
Module is part of the next kodi log uploader version. 

https://github.com/XBMC-Addons/script.kodi.loguploader/pull/1

**Comment by Razzeee** [comment]
Any reason why you didn't check the checkmarks?

**Comment by Lunatixz** [comment]
Only three right? They were definitely all checked when I submitted. I'll recheck them.... Thanks

**Comment by Lunatixz** [comment]
BTW I reviewed codacy comments, all notable points but nothing that impacts the stability of the code.

**Comment by learningit** [comment]
Assuming that this is a new script, the first problem is the Helix branch is closed for new submissions.
Please see: http://kodi.wiki/view/Submitting_Add-ons
I believe we are only taking new submissions for Jarvis and above.

**Comment by Lunatixz** [comment]
Okay i'll delete this branch and resubmit...

**Pull request closed without merging**
