### PR TITLE
[service.subtitles.pipocas] 0.17.6 Enhance the code & apply some fixes

### PR DESCRIPTION
**Pull request by highlandr**
Code cleaning
Refactor some code
Enhance translation
Fix some typos on variables
Enhance login code

### CODE REVIEW

**Comment by enen92** [comment]
@highlandr please fix the pull request, you're submitting changes to legendasdivx, legendaszone, pipocas, etc in the same pull request

**Comment by enen92** [comment]
If you need help just let me know and I'll PR on your behalf

**Comment by highlandr** [comment]
If you can that would be great :)
Not a git expert and been a while... had to install some tools as well :)
cheers!

**Comment by highlandr** [comment]
I will send a new PR.
There's a new version compatible with Python3 and Matrix.
I will do it right this time :)
Hopefully.

Thanks.

**Pull request closed without merging**
