### PR TITLE
[script.artistslideshow] 2.1.4

### PR DESCRIPTION
**Pull request by pkscout**
### Description
v.2.1.4
- fix for fallback images not showing if all artists on a multi-artist song have no images
- converted language files to current format for forward compatibility
### Checklist:

- [ x ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ x ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [ x ] Each add-on submission should be a single commit with using the following style: [script.foo.bar] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by pkscout** [comment]
I **think** the complex entry point test is new.  If that's a requirement moving forward I can look at rewriting AS for the next major release (on which I'm working now), but I'm hoping you all will accept the minor updates this time, as this is the last non-Leia version bug fix I'm likely to do.

**Comment by Rechi** [comment]
Is there any reason for not updating the add-on in [helix branch](https://github.com/xbmc/repo-scripts/tree/helix/script.artistslideshow) as there is only a very small code changed (see below)? 

```
--- a/script.artistslideshow/default.py
+++ b/script.artistslideshow/default.py
@@ -684,8 +684,9 @@
     def _merge_images( self ):
         lw.log( ['merging files from primary directory %s into merge directory %s' % (self.CacheDir, self.MergeDir)] )
-        self.MergedImagesFound = True
+        self.MergedImagesFound = False
         dirs, files = xbmcvfs.listdir(self.CacheDir)
         for file in files:
             if(file.lower().endswith('tbn') or file.lower().endswith('jpg') or file.lower().endswith('jpeg') or file.lower().endswith('gif') or file.lower().endswith('png')):
+                self.MergedImagesFound = True
                 img_source = os.path.join( self.CacheDir, smartUTF8( file ).decode( 'utf-8' ) )
                 img_dest = os.path.join( self.MergeDir, itemHash( img_source ) + getImageType( img_source ) )               
```
\
CI only fails if errors are reported. Warnings would be nice to get fixed, but don't let CI fail.

**Comment by pkscout** [comment]
The other thing that changed was the format of all the language files.  My understanding is that the new language file format is only compatible with Krypton and Leia.  I guess I could back out the language file changes and then resubmit if desired.

**Comment by Rechi** [comment]
Yes the language files would have to be renamed to their old names.
It's your decision if you want to updated the helix version or only submit the fix to krypton and higher.

Let me know which option you are choosing, so that I can either review this PR or ignore it.

**Comment by pkscout** [comment]
I did a little github-fu and undid the language file changes so that this final small update will be good for Helix forward.  I'll close this PR and open another one with the Helix compatible stuff.

**Pull request closed without merging**
