### PR TITLE
[script.module.protobuf3] v3.0.0

### PR DESCRIPTION
**Pull request by WoLpH**
Added the protobuf3 addon as discussed in #263 

@ronie is this ok? :)

### CODE REVIEW

**Comment by ronie** [comment]
1. you're missing the xbmc.python requirement in your addon.xml

2. you need to rename the protobuf folder to protobuf3, and update your addon.xml file to reflect this change

**Comment by WoLpH** [comment]
Both fixed :)

**Comment by ronie** [comment]
thx!

one thing i forgot to mention (sorry) is we only add new script modules to our repo if there's at least one other addon in our repo that needs it.

**Comment by WoLpH** [comment]
That's a bit of a chicken-and-egg problem isn't it? ;)

j/k. I'm reworking the hyperion addon so that will be using this one quite soon.

**Comment by ronie** [comment]
:-)
k, we'll wait till you've finished it and add both at the same time.

**Comment by WoLpH** [comment]
@ronie it seems I may have encountered a bug in Kodi. As soon as I rename the folder to anything other than "lib" it stops functioning (in Kodi Jarvis at least).

**Comment by WoLpH** [comment]
There's already a working version here: https://github.com/WoLpH/kodi-protobuf/

But it doesn't work for Android yet so I'm still debugging that issue. I expect to have a release this weekend.

**Comment by ronie** [comment]
i'm closing this one as it seems stalled.
feel free to ping me here if it needs to get resurrected.

**Comment by WoLpH** [comment]
Sure, sounds good. Besides getting the latest version I don't believe
there's any real benefit to version 3 at this time anyhow.

**Pull request closed without merging**
