### PR TITLE
[script.module.enum@matrix] 0.4.7

### PR DESCRIPTION
**Pull request by joaopa00**
### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by joaopa00** [comment]
It would be nice if we can receive some feedbacks for this PR. Thanks in advance.

**Review by basrieter — APPROVED** [review]

**Comment by basrieter** [comment]
What add-on will be using this @joaopa00 ?

**Comment by joaopa00** [comment]
Thanks for the feedback.
Enum is requested by [https://github.com/xbmc/repo-plugins/pull/4113](url)

**Comment by basrieter** [comment]
> Thanks for the feedback. Enum is requested by [catchuptvandmore(https://github.com/[xbmc/repo-plugins/pull/4113](https://github.com/xbmc/repo-plugins/pull/4113))

But that is an add-on a `krypton` branch. It won't work if `enum` is in Matrix. There seems to be a mix-up in branches/Python versions. That should be somehow solved first.

**Comment by joaopa00** [comment]
I removed the dependency on this module of my addon 
Thanks for your help anyway.

**Pull request closed without merging**
