### PR TITLE
[service.upnext] v1.0.0

### PR DESCRIPTION
**Pull request by im85288**
### Description
This will be my replacement for service.nextup.notification for Leia and onwards. The addon shows a popup window to allow users to play the next up episode. 
### Checklist:

- [ x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [ x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by enen92** [comment]
@im85288 have you tested your service with py3 builds? The idea behind the leia branch is to only accept addons that are compatible with both python 2.7 and 3.0.

**Comment by Razzeee** [comment]
Here's the log btw

```
INFO: Checking add-on service.upnext
INFO: Created by im85288
INFO: Addon id matches folder name
failed validating '' with XsdPatternsFacet(['\\s*([^\\s]\\s*)+']):
Reason: value don't match any pattern of ['\\s*([^\\s]\\s*)+'].
Schema:
  <xs:pattern xmlns:xs="http://www.w3.org/2001/XMLSchema" value="\s*([^\s]\s*)+" />
Instance:
  <language />
Path: /extension/language
ERROR: Schema validation failed for the following points: xbmc.addon.metadata 
WARN: For leia it is advised to set xbmc.python version to 2.26.0
INFO: This is a new addon
INFO: Image icon exists
ERROR: Icon.png should be solid. It has transparency.
ERROR: Icon should have either 256x256 or 512x512 but it has 500x500
INFO: You might want to add a fanart
INFO: Image screenshot exists
INFO: Image screenshot exists
INFO: Image screenshot exists
INFO: Image screenshot exists
WARN: Complex entry point. Check: service.py | Counted lines: 47 | Lines allowed: 15
ERROR: We found 3 problems and 2 warnings, please check the logfile.
```

**Comment by im85288** [comment]
Thanks, is this `ERROR: Schema validation failed for the following points: xbmc.addon.metadata` actually an error? Do I need to fix all warnings too. Cheers

**Comment by Razzeee** [comment]
No, that one is actually fine as it's a bug. See here https://github.com/xbmc/addon-check/issues/133

Usually we like `WARN: For leia it is advised to set xbmc.python version to 2.26.0` to be fixed, as it's an easy one.

We do understand that the entrypoint one can be not as easy to fix, so it's optional (thus a warning) but it brings significant improvements, so we encourage you to fix it at some point in time.

**Comment by Rechi** [comment]
> Each add-on submission should be a single commit with using the following style: [script.foo.bar] v1.0.0

Please squash your commits to a single one.

**Comment by Razzeee** [comment]
Your fanart format is off btw
`ERROR: Fanart should have either 1280x720 or 1920x1080 or 3840x2160 but it has 1920x1200`

**Comment by Rechi** [comment]
No need to close this PR. To fix your pull request execute the following commands (origin is your repo, upstream is the xbmc repo)

```
git fetch upstream
git checkout leia
git reset --hard upstream/leia
git checkout origin/leia -- plugin.video.mlbtv/
git commit -m '[service.upnext] v1.0.0'
git push -f origin leia
```

**Comment by im85288** [comment]
Sorry I had already deleted my fork by the time I read this, I always get confused on how to do this but will keep it in mind if needed in the future

**Pull request closed without merging**
