### PR TITLE
[service.iptv.manager] 0.2.4+matrix.1

### PR DESCRIPTION
**Pull request by pihug12**
### Add-on details:

* **Add-on name:** IPTV Manager
* **Add-on ID:** service.iptv.manager
* **Version number:** 0.2.4+matrix.1
* **Kodi/repository version:** matrix
* **Code location:** https://github.com/add-ons/service.iptv.manager
* **Description:** IPTV Manager integrates IPTV channels from other add-ons in the Kodi TV and Radio menus.
* **Owners:** @michaelarnauts & @peno64

### Description of changes:

**v0.2.4 (2023-12-02)**

* Fix for Configure IPTV automatically.
* https://github.com/add-ons/service.iptv.manager/compare/v0.2.3...v0.2.4

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Review by pkscout — APPROVED** [review]

**Comment by Lunatixz** [comment]
@pihug12 Can you explain the need for this change?

**Comment by peno64** [comment]
@Lunatixz 

I can do that. 

service.iptv.manager changes the configuration of iptv simple client to be able to work. That has always been so since the beginning of service.iptv.manager
However since Kodi Matrix this didn't work anymore because for some reason the configuration file of iptv simple client now has a different name. This fix searches the new name and adapts that one such that service.iptv.manager works again.

**Comment by Lunatixz** [comment]
Changing the settings for another plugin are against repository rules! I suggest you contact the original developer for idea to solve your issue. THX

**Comment by peno64** [comment]
@Lunatixz 

Again, it has always been like that from  the beginning from this addon as developed from the original developer Michael Arnouts and it has been accepted at that time so why suddenly after that time not accept it. It is the only way how this addon *can* work.

**Comment by Lunatixz** [comment]
@peno64 I understand and IC you have a PR in the origin repository. However, this doesn't change that fact that you're copying files to another plugin; which is against repository guidelines. All changes to another plugins settings from a third-party are to be handled by Kodi's API. ie setsetting('foobar',true) at no point are blind copying files from one plugin to another allowed.

**Comment by Lunatixz** [comment]
@peno64 You might want to keep your eye on this PR https://github.com/xbmc/xbmc/pull/23648

**Pull request merged**
