### PR TITLE
[script.kodi.loguploader] 0.6.0

### PR DESCRIPTION
**Pull request by ronie**
### Description
paste.kodi.tv now allows file uploads up to 2MB.
this change is needed to make use of the new, increased limit.
### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by enen92** [comment]
@ronie version in jarvis is higher than the version in krypton, which affects the migration.
Ideally:

jarvis_version < krypton_version < matrix

**Comment by ronie** [comment]
@Rechi i'm not too pleased to find out you hijacked my addon: https://github.com/xbmc/repo-scripts/pull/1132
if you wish to contribute, you can PR your changes upstream.

**Comment by enen92** [comment]
Thanks for adjusting ronie

**Comment by enen92** [comment]
This branch is out-of-date with the base branch
Merge the latest changes from krypton into this branch.

You might need to rebase though

**Pull request merged**
