### PR TITLE
[script.module.ttml2ssa] 0.3.4

### PR DESCRIPTION
**Pull request by Paco8**
### Description

Ttml2Ssa is a library that allows other addons to convert TTML/XML/DFXP/VTT/SRT subtitles to SRT and SSA/ASS formats. It also provides a configuration window where the user can adjust the SSA/ASS style and other options.

Website: https://github.com/Paco8/ttml2ssa
### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by Paco8** [comment]
Hello. Any problem?

**Comment by basrieter** [comment]
What add-on will be using this module? We only accept modules until there is an add-on that starts using it. Are you also planning a Matrix (Python 3) version?

**Comment by Paco8** [comment]
I've patched the Netflix, Amazon VOD and hbogoeu addons to use ttml2ssa (you can find them [in my test repo](https://github.com/Paco8/kodi-repo)).

I haven't submitted pull requests yet to those addons because I thought it would be easier for them to accept them if ttml2ssa is in the official repository. Since the ttml2ssa settings are shared among all the addons I think it would be a mess if every addon had to include a copy of ttml2ssa.

Yes, there's a version for matrix, I've just submitted the leia version first.

**Comment by enen92** [comment]
Hbo go is in the repo so this is actually up to the developer to decide

**Comment by ronie** [comment]
Since no addon is using this, we cannot merge it into our repo.
feel free to reopen this PR whenever there is a pull-request for an addon that needs this module.

**Pull request closed without merging**
