### PR TITLE
add omega repo

### PR DESCRIPTION
**Pull request by fuzzard**
### Description
Omega Repo
### Checklist:

- [ ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [ ] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by ronie** [comment]
i don't recall if it's actually needed, but it might be best to first create the omega branch in all the repos before pulling this one in.

other than that, looks good to me.

**Comment by fuzzard** [comment]
Ok, i'll look into that at the end of the week.

Question regarding this however, just for future reference, what if an api version changes during a release cycle for whatever reason? do we just update in here, or in general are there processes in place where it doesnt actually matter for this?

**Comment by ronie** [comment]
i don't think we ever changed an api version halfway through a release cycle and i don't think we ever should :-)

but since we specify the 'minimum' required version here, it might not have much of an impact if we did do an api bump.

**Comment by fuzzard** [comment]
Have created an omega branch, and opened PR's to clean it up (most branches created off master, then a PR to bring it up to date with yml/other stuff)

https://github.com/xbmc/repo-scripts/pull/2410
https://github.com/xbmc/repo-resources/pull/352
https://github.com/xbmc/repo-plugins/pull/4258
https://github.com/xbmc/repo-skins/pull/385

repo-webinterfaces has just been branched (no cleanup PR needed)
repo-scrapers i PR'd and merged

**Review by enen92 — APPROVED** [review]

**Pull request merged**
