### PR TITLE
[script.module.simpleplugin3@matrix] 3.0.5+matrix.1

### PR DESCRIPTION
**Pull request by vlmaksime**
### Add-on details:

- **General**
  - Add-on name: SimplePlugin 3
  - Add-on ID: script.module.simpleplugin3
  - Version number: 3.0.5+matrix.1
  - Kodi/repository version: matrix

- **Code location**
  - URL: https://github.com/romanvm/script.module.simpleplugin
  
SimplePlugin micro-framework that simplifies Kodi content plugin programming.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by vlmaksime** [comment]
This add-on used at weather.gismeteo

**Comment by rickybiscus** [comment]
@vlmaksime : plugin is also used here (included as file since the dependency cannot currently be loaded automatically): https://github.com/rickybiscus/plugin.video.auvio

**Comment by Lunatixz** [comment]
@vlmaksime Have you tried reaching out to @romanvm ? This is his module updates must come from him unless you are authorized by him to update the module.

**Comment by romanvm** [comment]
I don't develop this specific project and gave contributor rights to @vlmaksime long time ago so this is essentially his project now. I guess I need to transfer ownership as well to make this official.

**Review by ronie — APPROVED** [review]
looks good to me, thx!

**Pull request merged**
