### PR TITLE
[script.module.metadatautils] 1.0.0

### PR DESCRIPTION
**Pull request by marcelveldt**
### Description
Module for artwork/metadata from various sites. Another piece of the puzzle in splitting up my skinhelper addon into several smaller parts. This module will be used by some of my addons (also to be submitted) and can be used by other devs. As the module makes use of caching the online resources (with the simplecache addon), I think it's a great start to prevent 100's of addons grabbing the same info from online resources. Instead addons can grab the metadata from this module which will handle the scraping and caching. I did my best to format the dicts as close as possible to the kodi terminology.
### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [sciprt.foo.bar] v1.0.0

### CODE REVIEW

**Comment by marcelveldt** [comment]
any word on this ?

**Comment by phil65** [comment]
Looks ok (quick review only though)
Wouldnt it make sense to rename this module before releasing it here? It doesnt seem to exclusively deal with art. ;)

**Comment by marcelveldt** [comment]
@phil65 the id of the script is script.module.skin.helper.artutils but as a name I used "Skin Helper Artwork and metadata Module" 

While it first started as a module for my skin helper scripts, it has become a metadata module for all kind of online sources useful for other addons.

I have no issue in changing the id/name but I have do not have some good idea right now :-) 
Maybe this:

ID: script.module.metadata-utils
Name: Kodi artwork and metadata module

Let me know if you want me to change the id/name or leave it like this. BTW maybe some of the stuff in the module is useful in your addons too.

**Comment by phil65** [comment]
script.module.metadatautils perhaps?

**Comment by marcelveldt** [comment]
Great idea. I will go ahead and change it now that I still can.
Shall I close this one and submit a new PR or just modify this one aquashing the commits ?

**Comment by phil65** [comment]
both fine.

**Comment by marcelveldt** [comment]
OK, updated commit is coming up asap. Please also holf off with my other PR's so I have the chance to update them with the new module ID

**Comment by phil65** [comment]
sure, thx.

**Comment by marcelveldt** [comment]
@phil65 update the addon ID, the other PR's are also adjusted so it's all good to go

**Comment by ronie** [comment]
thx!

**Pull request merged**
