### PR TITLE
[screensaver.digitalclock] 3.8.0

### PR DESCRIPTION
**Pull request by vdb86**
### Description
Added support for custom position and now playing thumbnails.
Had to edit the rest of the files too so that everything looks good.
### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [sciprt.foo.bar] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@ronie @phil65 can you check skinning stuff ?

**Comment by ronie** [comment]
looks ok to me.

**Comment by vdb86** [comment]
There are no major changes in functionality.
I had to rename some stuff so that it makes more sense now with new options.
Completely changed the strings, preparing for Attila and Transifex.

**Comment by phil65** [comment]
lot of the xmls use stringcompare(), so this script will be broken for v18.
I also wonder why this doesnt use the regular way of adding support for different skins?
All xmls are inside skin/default/...

**Comment by vdb86** [comment]
Hi phil65!
I'm not a real programmer, I'm an electrical engineer, so when I started creating this it was rather hard, I had to learn a lot of stuff about python, xmls and how Kodi does certain things.
I've found quite a few things that weren't documented anywhere and were causing issues here and there.
I'm sure whoever is a real programmer and knows all of the things above probably wants to kill himself when he sees my work, but unfortunately at this point I'm not capable of creating something better :(

When I realized that I can's specify my own fonts I moved to an idea of storing font names and sizes in the default.py and just using controls for changing them according to the current skin.
For some reason that can't be done - if you take a look at the xmls they are all the same, the only differences are the fonts and font sizes.
I couldn't even directly control the color of text, had to do it indirectly...

If you're willing to through me in the right direction, or help me in any way I'll gladly fix whatever needs fixing...

**Pull request merged**
