### PR TITLE
[service.subtitles.subtitle] 4.4.5 && [service.subtitles.subscenter] 4.0.5

### PR DESCRIPTION
**Pull request by CaTzil**
### Description

* Fix Hebrew titles pattern matching
* Update logo & icon
* Add mirroring of subs

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a sinlge commit with using the following style: [sciprt.foo.bar] v1.0.0

Addtional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuesly monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by CaTzil** [comment]
Fix the changelog, thank you for notice.

**Comment by phil65** [comment]
looks ok. Please make a different PR for each update in the future.

**Comment by CaTzil** [comment]
OK,
Can someone merge it?
BTW, There is no way to do 2 separate PR from the same branch.
If you create a PR and then commit to your branch, that commit will be added to the **open** PR.

**Comment by phil65** [comment]
well, you shouldnt use the same branch then. ;)
Create a new branch for each add-on.

**Pull request merged**
