### PR TITLE
[screensaver.digitalclock] 3.6.0

### PR DESCRIPTION
**Pull request by vdb86**
I guess third time's the charm :)
Hopefully now everything is in order.

### CODE REVIEW

**Comment by learningit** [comment]
Do you require script.sleep or was that just spurious code in the last PR?
If so, you should add as a dependency in addon.xml and also submit a separate PR for the script.sleep changes.
Other than that looks good to me - please  next time fix the \__path\__ labels to something that doesn't resemble an python internal label

**Comment by vdb86** [comment]
As far as I see script.sleep appears if I sync xbmc/isengard with my own in github program on windows.
The funny thing is that if I compare those two on githib itself there are no differences.
script.sleep was merged yesterday, not sure why it pops up on my end.

No problem, I'll get that fixed with the next release!

**Comment by learningit** [comment]
In my experience, that usually mean that a sync or rebase is needed to get the windows git up to date. I also notice under Win 8 there is an occasional delay in getting the versions of git files fully updated, so if I'm doing things fast, I sometimes have a file or two which are out of sync. I usually rebase at that point.

**Comment by learningit** [comment]
Also I make sure that I always create the new branch from the xbmc repo branches, not the local ones I created for a previous PR.

**Comment by vdb86** [comment]
That's exactly how I avoided the whole script.sleep problem :)
I didn't use a local branch for creating mine, but instead used the xbmc repo branch.
Unfortunately rebasing and squashing stuff is till too advanced for me, until I figure out how to click somewhere and take care of it.
I'm usually fine with command line if I start with it, but if I'm used to a GUI than command line is a no go.

Thanks for all the info and help, most of all for your patience!

**Pull request merged**
