### PR TITLE
[script.module.pycountry] 17.5.14b

### PR DESCRIPTION
**Pull request by Lunatixz**
### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by learningit** [comment]
Still looking into this. If you want it for your own use and not wait on adding it as a pypi library, you'll need to rename it to avoid conflicts if and when it's added as a pypi library.

**Comment by Lunatixz** [comment]
what does pypi library have to do with kodis repo? i'm confused... distros do not cohabitate with kodis repo, am I wrong? almost all modules hosted here are also hosted via pypi. I'm almost sure it's a non issue.

**Comment by learningit** [comment]
I've discussed this with Team Kodi members, I was pretty sure but not certain of the rules. I have confirmed them with the team.
It can be an issue. Please explain what you've modified.
Definitely the version number needs to follow the pypi version or the module name needs to differ.
Generally to be accepted in the kodi.org repo, everything in the name/lib directory should be identical to the pypi version.  The version in the addon.xml should also be identical to the pypi version. 

You can have a look at an existing script.module such as:
https://github.com/xbmc/repo-scripts/tree/gotham/script.module.beautifulsoup4

**Comment by Lunatixz** [comment]
Can you expand on the conflict that arises? I'm trying to understand the inner workings for Kodi and was unaware that there is a issue with script.modules vs their existing distros. I've submitted a number of modules in the past, this is the first i'm hearing of this.

Below is an example of modicatoin made to allow file access within Kodis VFS:
https://github.com/Lunatixz/XBMC_Addons/blob/master/script.module.pycountry/lib/pycountry/__init__.py#L19

I generally use the version number identical with the sources release, unless I made amendments, where I add a subversion tag 'a', 'b', etc.

THX

**Comment by Lunatixz** [comment]
BTW, The only reason for submitting this module was in hope that other developers would use it, rather than individual plugin developers including hefty tables with each submissions. pycountry includes various  tables for every region in a easy to use format. Below is an example from plutotv:
https://github.com/Lunatixz/XBMC_Addons/blob/master/plugin.video.plutotv/country.py

**Comment by enen92** [comment]
IIRC script modules take an higher priority than those installed on the system for platforms using system python. Usually when you package an existing python module as a script module you just take the module code (from pypi) and give credits to the original author. If you change the original module code, the module is no longer the same and so, as a means to avoid confusion, you should rename/rebrand it (if the license complies).
So, if the code has any changes, the best solution is to rename it/fork it and you to be the author.

**Comment by Lunatixz** [comment]
k i'm going to rename it to pycountries and resubmit.

**Pull request closed without merging**
