### PR TITLE
[script.module.selenium] 3.141.59.001

### PR DESCRIPTION
**Pull request by tingjhenjiang**
[script.module.selenium] 3.141.59.001

### Description
selenium ( [the original project is here](https://github.com/SeleniumHQ/selenium) ) is a famous browser testing tool and often be used to emulate browser behaviors. It is a great tool to help addon developers to fetch webpage information especially when there are many websites adopt javascripts.

I packed essential parts of this project release(**source version is 3.141.59**) and make it a script.module addon to allow developers to easily import them. 

This package includes only python webdriver library. Other webdriver executable binaries (e.g. webdriver.exe ...) are not included because they are platform-dependent and binaries update frequently and the correspondent webdriver needs to match them, and users may still provide the path to binaries by settings. 

Usage is simple and identical to original library. For example,
`from selenium import webdriver`
`from selenium.webdriver.chrome.options import Options as ChromeOptions`
`chromeoptions = ChromeOptions()`
`chromeoptions.binary_location = chromebinary_location`
`driver = webdriver.Chrome(executable_path=chromedriver_path, options=chromeoptions, desired_capabilities=chrome_desired_capabilities)`

or `driver = webdriver.Firefox(executable_path=geckodriver_path, firefox_binary=firefoxbinary_location, firefox_profile=firefoxprofile, firefox_options=firefoxoptions, desired_capabilities=firefoxcaps, log_path=self.seleniumlogpath)`

I have tested them in my own addon project built upon Kodi Leia.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by enen92** [comment]
What about the webdriver/binary component? How will that work?

**Comment by tingjhenjiang** [comment]
> What about the webdriver/binary component? How will that work?

I have mentioned that in the top post and gave some examples.
It's just like [script.module.request](https://kodi.wiki/view/Add-on:Requests) or [script.module.simplejson](https://kodi.wiki/view/Add-on:Simplejson). They are basis of other potential package/addons.
The existence of script.module is to make potential project to appear. Not to mention I might publish my project which uses this package.

**Comment by enen92** [comment]
No sorry, the rule for inclusion of script.modules in our repo is to have an addon that consumes and depends on that script module. So, until there isn't a project that uses the module, it won't be merged.

**Comment by enen92** [comment]
Closing as no activity and no main add-on has been submitted?

**Pull request closed without merging**
