### PR TITLE
[script.module.web-pdb] 1.2.2

### PR DESCRIPTION
**Pull request by romanvm**
### Description

This is a remote debugger for Kodi Python addons: http://forum.kodi.tv/showthread.php?tid=292141

`xbmc.python.script` extension point is needed to allow manual installing via Kodi UI. AFAIK currently you cannot install library addons manually (though previously you could).

### Checklist:

- [ x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [ x] Each add-on submission should be a sinlge commit with using the following style: [sciprt.foo.bar] v1.0.0

### CODE REVIEW

**Comment by phil65** [comment]
Code looks good, but please choose an icon with a solid background. :)

**Comment by romanvm** [comment]
I don't have any other freely available icon.

**Comment by phil65** [comment]
just put a white backgorund behind it instead of transparency.

**Comment by romanvm** [comment]
I have used another icon.

**Comment by phil65** [comment]
Thx. To me all looks good now.

**Comment by Razzeee** [comment]
I think we can merge this, if phil did not find anything wrong ;)

**Comment by Razzeee** [comment]
@bignoid what's going on?

**Comment by BigNoid** [comment]
Not sure, may have pressed this accidentally while viewing on my iPad. Sorry about that :/

**Pull request merged**
