### PR TITLE
[script.module.dropbox] 10.3.1

### PR DESCRIPTION
**Pull request by robweber**
### Description
This updates the Dropbox library to version 10.3.1. This is not the newest version available, but it does have support for short lived access tokens, and refresh tokens. This is important as Dropbox issues short lived (4 hour) oauth tokens by default now. Support for refresh tokens avoids having to constantly re-authorize applications. 

10.3.1 was chosen instead of new versions as this is the last version prior to the [Dropbox Stone library](https://github.com/dropbox/stone) being separated in to it's own module. Using a newer version would require also creating a Kodi module for the Stone library, which was less than ideal. Addon authors should be able to use this as a drop-in replacement in current projects and can write new code to take advantage of the refresh token feature. 

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by robweber** [comment]
I know you probably get a lot of these stacked up but wanted to ping this to check the status. Once this is merged in I can publish an update to the Backup addon to fix the broken Dropbox functionality (constant re-auth)

**Comment by romanvm** [comment]
I started reviewing it but cannot give you any estimation considering the sheer size of the PR. Some files have have dozens of thousands lines of code and GitHub cannot even display the biggest files that have over 25K and over 100K lines of code.

**Comment by robweber** [comment]
I understand. It's 99.9% the same as the library Dropbox published aside from a small change to get the `pkg_resources` library to load correctly (this change was made to the current Kodi addon version as well). It's too bad there isn't an easier way to review these when they're libraries being added and not Kodi-specific addons. Appreciate the update, I'll be patient!

**Review by romanvm — APPROVED** [review]
LGTM. I've just compared md5 hashes for the biggest files.

**Pull request merged**
