### PR TITLE
[script.module.archive_tool] 2.0

### PR DESCRIPTION
**Pull request by zach-morris**
For Matrix
https://github.com/zach-morris/script.module.archive_tool

### Description

archive_tool is a set of common python functions to work with the Kodi archive virtual file system (vfs) binary addons such as vfs.libarchive and vfs.rar

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by enen92** [comment]
Hey @zach-morris is there any addon using this module?

**Comment by enen92** [comment]
If the code is exacly identical to the one in Leia (with just the addon.xml change) you probably want to version this differently and use PEP440 local version identifiers. 

in leia: `1.13.0`
in matrix: `1.13.0+matrix.1`

That way we know this is the same version

**Comment by zach-morris** [comment]
OK, thanks.  I'll resolve these

**Comment by enen92** [comment]
Policy has always been: script.modules to be in the repo must be a dependency of any addon that actually uses it. So, probably not a bad idea to submit your addon to the official repo. If your addon is the only one using this dependency and is shared in an external repo, maybe the place for the module is also in the external repo.

Ah it seems to be @highlandr. Maybe he can already start to use it as a dependency in his submissions?

**Comment by zach-morris** [comment]
Yes probably @highlander would be the reason to submit it at this point then.  I can't submit IAGL since it contains shell scripts (which I think are against the rules) for external launching of programs.  I can put this module in my external repository for now.

**Comment by highlandr** [comment]
Zach do whatever you want atm, you can delay, I put your name on the "news" :)
When you release this I will use it. I don't use vfs.libarchive just vfs.rar.
You can check the code in my git.

**Comment by zach-morris** [comment]
OK, sounds like close this and put it in my repository then for now.  Thanks

**Pull request closed without merging**
