### PR TITLE
[script.module.pycountry] 17.5.14

### PR DESCRIPTION
**Pull request by Lunatixz**
https://pypi.python.org/pypi/pycountry

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by Lunatixz** [comment]
Dependency for upcoming PlutoTV update.

**Comment by learningit** [comment]
Is this straight up from pipy or modified? 
If it's modified, the name will need to change to avoid conflicts.
If it's straight up, I've asked some others how we normally deal with putting pipy modules into the repo, I don't think it would be hosted in your repo. So I'll come back to you on this when I find out.

**Comment by Lunatixz** [comment]
Is there already a pycountry module? The submission of this module should be the same as all my past modules submission?

**Comment by Lunatixz** [comment]
I need to further port the module it appears some stock python modules are unavailable in the Android build? I'll resubmit tonight.

**Comment by learningit** [comment]
I'm not sure, that's why I'm checking with others. If it's an unmodified
pipy module, I would think that we would add it so everyone could use and
we would  manage the updates to it directly, rather than through your repo.
I could be wrong. I should get an answer shortly.

On Jun 16, 2017 2:16 PM, "Lunatixz" <notifications@github.com> wrote:

Is there already a pycountry module? The submission of this module should
be the same as all my past modules submission?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/xbmc/repo-scripts/pull/533#issuecomment-309097593>, or mute
the thread

**Comment by Lunatixz** [comment]
its modified, and i'd assume all modules are maintained by the developer who submitted them? At least that's how I view it... I've submitted a few modules and when needed will update when needed.

**Pull request closed without merging**
