### PR TITLE
[service.unmanic] 0.0.4

### PR DESCRIPTION
**Pull request by Josh5**
### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Review by basrieter — CHANGES_REQUESTED** [review]
Please **don't include all the libraries**, but use the provided Kodi libraries (such as the Requests library) via the addon.xml imports. See https://kodi.wiki/view/Addon.xml

Only submit your own code (and don't include the .gitignore file).

**Comment by Josh5** [comment]
Is that the only issue? 

I don't want to create a bunch of python modules for Kodi only to have you reject the rest of this add-on on some other merit. If you are going to reject it for something else (such as the JavaScript files etc), I would rather just close this PR.

I am happy to split out the modules and create PRs for all the missing ones and use the already available python modules, such as requests, in the Kodi repos.
I will also split out the Unmanic python module into its own PR and update this PR with only the service.

Could you please let me know if the Unmanic python module is something that will be added if I submit the PR?

Thanks

**Comment by basrieter** [comment]
> Is that the only issue?
> 
> I don't want to create a bunch of python modules for Kodi only to have you reject the rest of this add-on on some other merit. If you are going to reject it for something else (such as the JavaScript files etc), I would rather just close this PR.
> 
> I am happy to split out the modules and create PRs for all the missing ones and use the already available python modules, such as requests, in the Kodi repos.
> I will also split out the Unmanic python module into its own PR and update this PR with only the service.
> 
> Could you please let me know if the Unmanic python module is something that will be added if I submit the PR?
> 
> Thanks

There are 2790 files in here. Many of them are basic Python modules or already exists as modules. Such as `requests`, `urllib3` etc. That needs to change.

**Comment by basrieter** [comment]
Any update for this?

**Comment by Josh5** [comment]
Not at this point in time.

**Pull request closed without merging**
