### PR TITLE
[service.nextup.notification] 1.0.18

### PR DESCRIPTION
**Pull request by im85288**

### CODE REVIEW

**Comment by learningit** [comment]
In player.py you have some long waits using xbmc.sleep() - I saw at least one with a value of 10000. This is no longer acceptable as it hangs Kodi on exit. For waits longer than a second xbmc.Monitor().waitForAbort() needs to be used. Please see http://mirrors.kodi.tv/docs/python-docs/15.x-isengard/xbmc.html#Monitor-waitForAbort for more info.

**Comment by im85288** [comment]
Thanks, that is resolved now with the latest commits.

**Comment by Razzeee** [comment]
Can you squash this down to one commit?

**Comment by im85288** [comment]
I tried to do that in the above commit, please note the version bump

**Comment by Razzeee** [comment]
Then you need to drop/skip the previous commits in the branch this PR is based upon.

**Comment by learningit** [comment]
You can look here to see how to do the squash:
https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by im85288** [comment]
I'll try again with a new commit, closing this one

**Comment by Razzeee** [comment]
You can force push to this branch, to update it. A new PR is not needed, but if it's easier go ahead.

**Pull request closed without merging**
